/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from CrunchExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object CrunchExerciseName {
    const val BICYCLE_CRUNCH: Int = 0
    const val CABLE_CRUNCH: Int = 1
    const val CIRCULAR_ARM_CRUNCH: Int = 2
    const val CROSSED_ARMS_CRUNCH: Int = 3
    const val WEIGHTED_CROSSED_ARMS_CRUNCH: Int = 4
    const val CROSS_LEG_REVERSE_CRUNCH: Int = 5
    const val WEIGHTED_CROSS_LEG_REVERSE_CRUNCH: Int = 6
    const val CRUNCH_CHOP: Int = 7
    const val WEIGHTED_CRUNCH_CHOP: Int = 8
    const val DOUBLE_CRUNCH: Int = 9
    const val WEIGHTED_DOUBLE_CRUNCH: Int = 10
    const val ELBOW_TO_KNEE_CRUNCH: Int = 11
    const val WEIGHTED_ELBOW_TO_KNEE_CRUNCH: Int = 12
    const val FLUTTER_KICKS: Int = 13
    const val WEIGHTED_FLUTTER_KICKS: Int = 14
    const val FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH: Int = 15
    const val WEIGHTED_FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH: Int = 16
    const val FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL: Int = 17
    const val FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL: Int = 18
    const val FROG_PRESS: Int = 19
    const val HANGING_KNEE_RAISE_OBLIQUE_CRUNCH: Int = 20
    const val WEIGHTED_HANGING_KNEE_RAISE_OBLIQUE_CRUNCH: Int = 21
    const val HIP_CROSSOVER: Int = 22
    const val WEIGHTED_HIP_CROSSOVER: Int = 23
    const val HOLLOW_ROCK: Int = 24
    const val WEIGHTED_HOLLOW_ROCK: Int = 25
    const val INCLINE_REVERSE_CRUNCH: Int = 26
    const val WEIGHTED_INCLINE_REVERSE_CRUNCH: Int = 27
    const val KNEELING_CABLE_CRUNCH: Int = 28
    const val KNEELING_CROSS_CRUNCH: Int = 29
    const val WEIGHTED_KNEELING_CROSS_CRUNCH: Int = 30
    const val KNEELING_OBLIQUE_CABLE_CRUNCH: Int = 31
    const val KNEES_TO_ELBOW: Int = 32
    const val LEG_EXTENSIONS: Int = 33
    const val WEIGHTED_LEG_EXTENSIONS: Int = 34
    const val LEG_LEVERS: Int = 35
    const val MCGILL_CURL_UP: Int = 36
    const val WEIGHTED_MCGILL_CURL_UP: Int = 37
    const val MODIFIED_PILATES_ROLL_UP_WITH_BALL: Int = 38
    const val WEIGHTED_MODIFIED_PILATES_ROLL_UP_WITH_BALL: Int = 39
    const val PILATES_CRUNCH: Int = 40
    const val WEIGHTED_PILATES_CRUNCH: Int = 41
    const val PILATES_ROLL_UP_WITH_BALL: Int = 42
    const val WEIGHTED_PILATES_ROLL_UP_WITH_BALL: Int = 43
    const val RAISED_LEGS_CRUNCH: Int = 44
    const val WEIGHTED_RAISED_LEGS_CRUNCH: Int = 45
    const val REVERSE_CRUNCH: Int = 46
    const val WEIGHTED_REVERSE_CRUNCH: Int = 47
    const val REVERSE_CRUNCH_ON_A_BENCH: Int = 48
    const val WEIGHTED_REVERSE_CRUNCH_ON_A_BENCH: Int = 49
    const val REVERSE_CURL_AND_LIFT: Int = 50
    const val WEIGHTED_REVERSE_CURL_AND_LIFT: Int = 51
    const val ROTATIONAL_LIFT: Int = 52
    const val WEIGHTED_ROTATIONAL_LIFT: Int = 53
    const val SEATED_ALTERNATING_REVERSE_CRUNCH: Int = 54
    const val WEIGHTED_SEATED_ALTERNATING_REVERSE_CRUNCH: Int = 55
    const val SEATED_LEG_U: Int = 56
    const val WEIGHTED_SEATED_LEG_U: Int = 57
    const val SIDE_TO_SIDE_CRUNCH_AND_WEAVE: Int = 58
    const val WEIGHTED_SIDE_TO_SIDE_CRUNCH_AND_WEAVE: Int = 59
    const val SINGLE_LEG_REVERSE_CRUNCH: Int = 60
    const val WEIGHTED_SINGLE_LEG_REVERSE_CRUNCH: Int = 61
    const val SKATER_CRUNCH_CROSS: Int = 62
    const val WEIGHTED_SKATER_CRUNCH_CROSS: Int = 63
    const val STANDING_CABLE_CRUNCH: Int = 64
    const val STANDING_SIDE_CRUNCH: Int = 65
    const val STEP_CLIMB: Int = 66
    const val WEIGHTED_STEP_CLIMB: Int = 67
    const val SWISS_BALL_CRUNCH: Int = 68
    const val SWISS_BALL_REVERSE_CRUNCH: Int = 69
    const val WEIGHTED_SWISS_BALL_REVERSE_CRUNCH: Int = 70
    const val SWISS_BALL_RUSSIAN_TWIST: Int = 71
    const val WEIGHTED_SWISS_BALL_RUSSIAN_TWIST: Int = 72
    const val SWISS_BALL_SIDE_CRUNCH: Int = 73
    const val WEIGHTED_SWISS_BALL_SIDE_CRUNCH: Int = 74
    const val THORACIC_CRUNCHES_ON_FOAM_ROLLER: Int = 75
    const val WEIGHTED_THORACIC_CRUNCHES_ON_FOAM_ROLLER: Int = 76
    const val TRICEPS_CRUNCH: Int = 77
    const val WEIGHTED_BICYCLE_CRUNCH: Int = 78
    const val WEIGHTED_CRUNCH: Int = 79
    const val WEIGHTED_SWISS_BALL_CRUNCH: Int = 80
    const val TOES_TO_BAR: Int = 81
    const val WEIGHTED_TOES_TO_BAR: Int = 82
    const val CRUNCH: Int = 83
    const val STRAIGHT_LEG_CRUNCH_WITH_BALL: Int = 84
    const val LEG_CLIMB_CRUNCH: Int = 86
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BICYCLE_CRUNCH to "BICYCLE_CRUNCH",
        CABLE_CRUNCH to "CABLE_CRUNCH",
        CIRCULAR_ARM_CRUNCH to "CIRCULAR_ARM_CRUNCH",
        CROSSED_ARMS_CRUNCH to "CROSSED_ARMS_CRUNCH",
        WEIGHTED_CROSSED_ARMS_CRUNCH to "WEIGHTED_CROSSED_ARMS_CRUNCH",
        CROSS_LEG_REVERSE_CRUNCH to "CROSS_LEG_REVERSE_CRUNCH",
        WEIGHTED_CROSS_LEG_REVERSE_CRUNCH to "WEIGHTED_CROSS_LEG_REVERSE_CRUNCH",
        CRUNCH_CHOP to "CRUNCH_CHOP",
        WEIGHTED_CRUNCH_CHOP to "WEIGHTED_CRUNCH_CHOP",
        DOUBLE_CRUNCH to "DOUBLE_CRUNCH",
        WEIGHTED_DOUBLE_CRUNCH to "WEIGHTED_DOUBLE_CRUNCH",
        ELBOW_TO_KNEE_CRUNCH to "ELBOW_TO_KNEE_CRUNCH",
        WEIGHTED_ELBOW_TO_KNEE_CRUNCH to "WEIGHTED_ELBOW_TO_KNEE_CRUNCH",
        FLUTTER_KICKS to "FLUTTER_KICKS",
        WEIGHTED_FLUTTER_KICKS to "WEIGHTED_FLUTTER_KICKS",
        FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH to "FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH",
        WEIGHTED_FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH to "WEIGHTED_FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH",
        FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL to "FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL",
        FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL to "FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL",
        FROG_PRESS to "FROG_PRESS",
        HANGING_KNEE_RAISE_OBLIQUE_CRUNCH to "HANGING_KNEE_RAISE_OBLIQUE_CRUNCH",
        WEIGHTED_HANGING_KNEE_RAISE_OBLIQUE_CRUNCH to "WEIGHTED_HANGING_KNEE_RAISE_OBLIQUE_CRUNCH",
        HIP_CROSSOVER to "HIP_CROSSOVER",
        WEIGHTED_HIP_CROSSOVER to "WEIGHTED_HIP_CROSSOVER",
        HOLLOW_ROCK to "HOLLOW_ROCK",
        WEIGHTED_HOLLOW_ROCK to "WEIGHTED_HOLLOW_ROCK",
        INCLINE_REVERSE_CRUNCH to "INCLINE_REVERSE_CRUNCH",
        WEIGHTED_INCLINE_REVERSE_CRUNCH to "WEIGHTED_INCLINE_REVERSE_CRUNCH",
        KNEELING_CABLE_CRUNCH to "KNEELING_CABLE_CRUNCH",
        KNEELING_CROSS_CRUNCH to "KNEELING_CROSS_CRUNCH",
        WEIGHTED_KNEELING_CROSS_CRUNCH to "WEIGHTED_KNEELING_CROSS_CRUNCH",
        KNEELING_OBLIQUE_CABLE_CRUNCH to "KNEELING_OBLIQUE_CABLE_CRUNCH",
        KNEES_TO_ELBOW to "KNEES_TO_ELBOW",
        LEG_EXTENSIONS to "LEG_EXTENSIONS",
        WEIGHTED_LEG_EXTENSIONS to "WEIGHTED_LEG_EXTENSIONS",
        LEG_LEVERS to "LEG_LEVERS",
        MCGILL_CURL_UP to "MCGILL_CURL_UP",
        WEIGHTED_MCGILL_CURL_UP to "WEIGHTED_MCGILL_CURL_UP",
        MODIFIED_PILATES_ROLL_UP_WITH_BALL to "MODIFIED_PILATES_ROLL_UP_WITH_BALL",
        WEIGHTED_MODIFIED_PILATES_ROLL_UP_WITH_BALL to "WEIGHTED_MODIFIED_PILATES_ROLL_UP_WITH_BALL",
        PILATES_CRUNCH to "PILATES_CRUNCH",
        WEIGHTED_PILATES_CRUNCH to "WEIGHTED_PILATES_CRUNCH",
        PILATES_ROLL_UP_WITH_BALL to "PILATES_ROLL_UP_WITH_BALL",
        WEIGHTED_PILATES_ROLL_UP_WITH_BALL to "WEIGHTED_PILATES_ROLL_UP_WITH_BALL",
        RAISED_LEGS_CRUNCH to "RAISED_LEGS_CRUNCH",
        WEIGHTED_RAISED_LEGS_CRUNCH to "WEIGHTED_RAISED_LEGS_CRUNCH",
        REVERSE_CRUNCH to "REVERSE_CRUNCH",
        WEIGHTED_REVERSE_CRUNCH to "WEIGHTED_REVERSE_CRUNCH",
        REVERSE_CRUNCH_ON_A_BENCH to "REVERSE_CRUNCH_ON_A_BENCH",
        WEIGHTED_REVERSE_CRUNCH_ON_A_BENCH to "WEIGHTED_REVERSE_CRUNCH_ON_A_BENCH",
        REVERSE_CURL_AND_LIFT to "REVERSE_CURL_AND_LIFT",
        WEIGHTED_REVERSE_CURL_AND_LIFT to "WEIGHTED_REVERSE_CURL_AND_LIFT",
        ROTATIONAL_LIFT to "ROTATIONAL_LIFT",
        WEIGHTED_ROTATIONAL_LIFT to "WEIGHTED_ROTATIONAL_LIFT",
        SEATED_ALTERNATING_REVERSE_CRUNCH to "SEATED_ALTERNATING_REVERSE_CRUNCH",
        WEIGHTED_SEATED_ALTERNATING_REVERSE_CRUNCH to "WEIGHTED_SEATED_ALTERNATING_REVERSE_CRUNCH",
        SEATED_LEG_U to "SEATED_LEG_U",
        WEIGHTED_SEATED_LEG_U to "WEIGHTED_SEATED_LEG_U",
        SIDE_TO_SIDE_CRUNCH_AND_WEAVE to "SIDE_TO_SIDE_CRUNCH_AND_WEAVE",
        WEIGHTED_SIDE_TO_SIDE_CRUNCH_AND_WEAVE to "WEIGHTED_SIDE_TO_SIDE_CRUNCH_AND_WEAVE",
        SINGLE_LEG_REVERSE_CRUNCH to "SINGLE_LEG_REVERSE_CRUNCH",
        WEIGHTED_SINGLE_LEG_REVERSE_CRUNCH to "WEIGHTED_SINGLE_LEG_REVERSE_CRUNCH",
        SKATER_CRUNCH_CROSS to "SKATER_CRUNCH_CROSS",
        WEIGHTED_SKATER_CRUNCH_CROSS to "WEIGHTED_SKATER_CRUNCH_CROSS",
        STANDING_CABLE_CRUNCH to "STANDING_CABLE_CRUNCH",
        STANDING_SIDE_CRUNCH to "STANDING_SIDE_CRUNCH",
        STEP_CLIMB to "STEP_CLIMB",
        WEIGHTED_STEP_CLIMB to "WEIGHTED_STEP_CLIMB",
        SWISS_BALL_CRUNCH to "SWISS_BALL_CRUNCH",
        SWISS_BALL_REVERSE_CRUNCH to "SWISS_BALL_REVERSE_CRUNCH",
        WEIGHTED_SWISS_BALL_REVERSE_CRUNCH to "WEIGHTED_SWISS_BALL_REVERSE_CRUNCH",
        SWISS_BALL_RUSSIAN_TWIST to "SWISS_BALL_RUSSIAN_TWIST",
        WEIGHTED_SWISS_BALL_RUSSIAN_TWIST to "WEIGHTED_SWISS_BALL_RUSSIAN_TWIST",
        SWISS_BALL_SIDE_CRUNCH to "SWISS_BALL_SIDE_CRUNCH",
        WEIGHTED_SWISS_BALL_SIDE_CRUNCH to "WEIGHTED_SWISS_BALL_SIDE_CRUNCH",
        THORACIC_CRUNCHES_ON_FOAM_ROLLER to "THORACIC_CRUNCHES_ON_FOAM_ROLLER",
        WEIGHTED_THORACIC_CRUNCHES_ON_FOAM_ROLLER to "WEIGHTED_THORACIC_CRUNCHES_ON_FOAM_ROLLER",
        TRICEPS_CRUNCH to "TRICEPS_CRUNCH",
        WEIGHTED_BICYCLE_CRUNCH to "WEIGHTED_BICYCLE_CRUNCH",
        WEIGHTED_CRUNCH to "WEIGHTED_CRUNCH",
        WEIGHTED_SWISS_BALL_CRUNCH to "WEIGHTED_SWISS_BALL_CRUNCH",
        TOES_TO_BAR to "TOES_TO_BAR",
        WEIGHTED_TOES_TO_BAR to "WEIGHTED_TOES_TO_BAR",
        CRUNCH to "CRUNCH",
        STRAIGHT_LEG_CRUNCH_WITH_BALL to "STRAIGHT_LEG_CRUNCH_WITH_BALL",
        LEG_CLIMB_CRUNCH to "LEG_CLIMB_CRUNCH"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
