/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from CurlExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object CurlExerciseName {
    const val ALTERNATING_DUMBBELL_BICEPS_CURL: Int = 0
    const val ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL: Int = 1
    const val ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL: Int = 2
    const val BARBELL_BICEPS_CURL: Int = 3
    const val BARBELL_REVERSE_WRIST_CURL: Int = 4
    const val BARBELL_WRIST_CURL: Int = 5
    const val BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL: Int = 6
    const val BEHIND_THE_BACK_ONE_ARM_CABLE_CURL: Int = 7
    const val CABLE_BICEPS_CURL: Int = 8
    const val CABLE_HAMMER_CURL: Int = 9
    const val CHEATING_BARBELL_BICEPS_CURL: Int = 10
    const val CLOSE_GRIP_EZ_BAR_BICEPS_CURL: Int = 11
    const val CROSS_BODY_DUMBBELL_HAMMER_CURL: Int = 12
    const val DEAD_HANG_BICEPS_CURL: Int = 13
    const val DECLINE_HAMMER_CURL: Int = 14
    const val DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD: Int = 15
    const val DUMBBELL_HAMMER_CURL: Int = 16
    const val DUMBBELL_REVERSE_WRIST_CURL: Int = 17
    const val DUMBBELL_WRIST_CURL: Int = 18
    const val EZ_BAR_PREACHER_CURL: Int = 19
    const val FORWARD_BEND_BICEPS_CURL: Int = 20
    const val HAMMER_CURL_TO_PRESS: Int = 21
    const val INCLINE_DUMBBELL_BICEPS_CURL: Int = 22
    const val INCLINE_OFFSET_THUMB_DUMBBELL_CURL: Int = 23
    const val KETTLEBELL_BICEPS_CURL: Int = 24
    const val LYING_CONCENTRATION_CABLE_CURL: Int = 25
    const val ONE_ARM_PREACHER_CURL: Int = 26
    const val PLATE_PINCH_CURL: Int = 27
    const val PREACHER_CURL_WITH_CABLE: Int = 28
    const val REVERSE_EZ_BAR_CURL: Int = 29
    const val REVERSE_GRIP_WRIST_CURL: Int = 30
    const val REVERSE_GRIP_BARBELL_BICEPS_CURL: Int = 31
    const val SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL: Int = 32
    const val SEATED_DUMBBELL_BICEPS_CURL: Int = 33
    const val SEATED_REVERSE_DUMBBELL_CURL: Int = 34
    const val SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL: Int = 35
    const val STANDING_ALTERNATING_DUMBBELL_CURLS: Int = 36
    const val STANDING_DUMBBELL_BICEPS_CURL: Int = 37
    const val STANDING_EZ_BAR_BICEPS_CURL: Int = 38
    const val STATIC_CURL: Int = 39
    const val SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: Int = 40
    const val SWISS_BALL_EZ_BAR_PREACHER_CURL: Int = 41
    const val TWISTING_STANDING_DUMBBELL_BICEPS_CURL: Int = 42
    const val WIDE_GRIP_EZ_BAR_BICEPS_CURL: Int = 43
    const val ONE_ARM_CONCENTRATION_CURL: Int = 44
    const val STANDING_ZOTTMAN_BICEPS_CURL: Int = 45
    const val DUMBBELL_BICEPS_CURL: Int = 46
    const val DRAG_CURL_WHEELCHAIR: Int = 47
    const val DUMBBELL_BICEPS_CURL_WHEELCHAIR: Int = 48
    const val BOTTLE_CURL: Int = 49
    const val SEATED_BOTTLE_CURL: Int = 50
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        ALTERNATING_DUMBBELL_BICEPS_CURL to "ALTERNATING_DUMBBELL_BICEPS_CURL",
        ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL to "ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL",
        ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL to "ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL",
        BARBELL_BICEPS_CURL to "BARBELL_BICEPS_CURL",
        BARBELL_REVERSE_WRIST_CURL to "BARBELL_REVERSE_WRIST_CURL",
        BARBELL_WRIST_CURL to "BARBELL_WRIST_CURL",
        BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL to "BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL",
        BEHIND_THE_BACK_ONE_ARM_CABLE_CURL to "BEHIND_THE_BACK_ONE_ARM_CABLE_CURL",
        CABLE_BICEPS_CURL to "CABLE_BICEPS_CURL",
        CABLE_HAMMER_CURL to "CABLE_HAMMER_CURL",
        CHEATING_BARBELL_BICEPS_CURL to "CHEATING_BARBELL_BICEPS_CURL",
        CLOSE_GRIP_EZ_BAR_BICEPS_CURL to "CLOSE_GRIP_EZ_BAR_BICEPS_CURL",
        CROSS_BODY_DUMBBELL_HAMMER_CURL to "CROSS_BODY_DUMBBELL_HAMMER_CURL",
        DEAD_HANG_BICEPS_CURL to "DEAD_HANG_BICEPS_CURL",
        DECLINE_HAMMER_CURL to "DECLINE_HAMMER_CURL",
        DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD to "DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD",
        DUMBBELL_HAMMER_CURL to "DUMBBELL_HAMMER_CURL",
        DUMBBELL_REVERSE_WRIST_CURL to "DUMBBELL_REVERSE_WRIST_CURL",
        DUMBBELL_WRIST_CURL to "DUMBBELL_WRIST_CURL",
        EZ_BAR_PREACHER_CURL to "EZ_BAR_PREACHER_CURL",
        FORWARD_BEND_BICEPS_CURL to "FORWARD_BEND_BICEPS_CURL",
        HAMMER_CURL_TO_PRESS to "HAMMER_CURL_TO_PRESS",
        INCLINE_DUMBBELL_BICEPS_CURL to "INCLINE_DUMBBELL_BICEPS_CURL",
        INCLINE_OFFSET_THUMB_DUMBBELL_CURL to "INCLINE_OFFSET_THUMB_DUMBBELL_CURL",
        KETTLEBELL_BICEPS_CURL to "KETTLEBELL_BICEPS_CURL",
        LYING_CONCENTRATION_CABLE_CURL to "LYING_CONCENTRATION_CABLE_CURL",
        ONE_ARM_PREACHER_CURL to "ONE_ARM_PREACHER_CURL",
        PLATE_PINCH_CURL to "PLATE_PINCH_CURL",
        PREACHER_CURL_WITH_CABLE to "PREACHER_CURL_WITH_CABLE",
        REVERSE_EZ_BAR_CURL to "REVERSE_EZ_BAR_CURL",
        REVERSE_GRIP_WRIST_CURL to "REVERSE_GRIP_WRIST_CURL",
        REVERSE_GRIP_BARBELL_BICEPS_CURL to "REVERSE_GRIP_BARBELL_BICEPS_CURL",
        SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL to "SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL",
        SEATED_DUMBBELL_BICEPS_CURL to "SEATED_DUMBBELL_BICEPS_CURL",
        SEATED_REVERSE_DUMBBELL_CURL to "SEATED_REVERSE_DUMBBELL_CURL",
        SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL to "SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL",
        STANDING_ALTERNATING_DUMBBELL_CURLS to "STANDING_ALTERNATING_DUMBBELL_CURLS",
        STANDING_DUMBBELL_BICEPS_CURL to "STANDING_DUMBBELL_BICEPS_CURL",
        STANDING_EZ_BAR_BICEPS_CURL to "STANDING_EZ_BAR_BICEPS_CURL",
        STATIC_CURL to "STATIC_CURL",
        SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION to "SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
        SWISS_BALL_EZ_BAR_PREACHER_CURL to "SWISS_BALL_EZ_BAR_PREACHER_CURL",
        TWISTING_STANDING_DUMBBELL_BICEPS_CURL to "TWISTING_STANDING_DUMBBELL_BICEPS_CURL",
        WIDE_GRIP_EZ_BAR_BICEPS_CURL to "WIDE_GRIP_EZ_BAR_BICEPS_CURL",
        ONE_ARM_CONCENTRATION_CURL to "ONE_ARM_CONCENTRATION_CURL",
        STANDING_ZOTTMAN_BICEPS_CURL to "STANDING_ZOTTMAN_BICEPS_CURL",
        DUMBBELL_BICEPS_CURL to "DUMBBELL_BICEPS_CURL",
        DRAG_CURL_WHEELCHAIR to "DRAG_CURL_WHEELCHAIR",
        DUMBBELL_BICEPS_CURL_WHEELCHAIR to "DUMBBELL_BICEPS_CURL_WHEELCHAIR",
        BOTTLE_CURL to "BOTTLE_CURL",
        SEATED_BOTTLE_CURL to "SEATED_BOTTLE_CURL"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
