/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from HipRaiseExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object HipRaiseExerciseName {
    const val BARBELL_HIP_THRUST_ON_FLOOR: Int = 0
    const val BARBELL_HIP_THRUST_WITH_BENCH: Int = 1
    const val BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE: Int = 2
    const val WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE: Int = 3
    const val BRIDGE_WITH_LEG_EXTENSION: Int = 4
    const val WEIGHTED_BRIDGE_WITH_LEG_EXTENSION: Int = 5
    const val CLAM_BRIDGE: Int = 6
    const val FRONT_KICK_TABLETOP: Int = 7
    const val WEIGHTED_FRONT_KICK_TABLETOP: Int = 8
    const val HIP_EXTENSION_AND_CROSS: Int = 9
    const val WEIGHTED_HIP_EXTENSION_AND_CROSS: Int = 10
    const val HIP_RAISE: Int = 11
    const val WEIGHTED_HIP_RAISE: Int = 12
    const val HIP_RAISE_WITH_FEET_ON_SWISS_BALL: Int = 13
    const val WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL: Int = 14
    const val HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: Int = 15
    const val WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: Int = 16
    const val HIP_RAISE_WITH_HEAD_ON_SWISS_BALL: Int = 17
    const val WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL: Int = 18
    const val HIP_RAISE_WITH_KNEE_SQUEEZE: Int = 19
    const val WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE: Int = 20
    const val INCLINE_REAR_LEG_EXTENSION: Int = 21
    const val WEIGHTED_INCLINE_REAR_LEG_EXTENSION: Int = 22
    const val KETTLEBELL_SWING: Int = 23
    const val MARCHING_HIP_RAISE: Int = 24
    const val WEIGHTED_MARCHING_HIP_RAISE: Int = 25
    const val MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL: Int = 26
    const val WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL: Int = 27
    const val REVERSE_HIP_RAISE: Int = 28
    const val WEIGHTED_REVERSE_HIP_RAISE: Int = 29
    const val SINGLE_LEG_HIP_RAISE: Int = 30
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE: Int = 31
    const val SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH: Int = 32
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH: Int = 33
    const val SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL: Int = 34
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL: Int = 35
    const val SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER: Int = 36
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER: Int = 37
    const val SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL: Int = 38
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL: Int = 39
    const val SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: Int = 40
    const val WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL: Int = 41
    const val WEIGHTED_CLAM_BRIDGE: Int = 42
    const val SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL: Int = 43
    const val CLAMS: Int = 44
    const val INNER_THIGH_CIRCLES: Int = 45 // Deprecated do not use
    const val INNER_THIGH_SIDE_LIFT: Int = 46 // Deprecated do not use
    const val LEG_CIRCLES: Int = 47
    const val LEG_LIFT: Int = 48
    const val LEG_LIFT_IN_EXTERNAL_ROTATION: Int = 49
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BARBELL_HIP_THRUST_ON_FLOOR to "BARBELL_HIP_THRUST_ON_FLOOR",
        BARBELL_HIP_THRUST_WITH_BENCH to "BARBELL_HIP_THRUST_WITH_BENCH",
        BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE to "BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE",
        WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE to "WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE",
        BRIDGE_WITH_LEG_EXTENSION to "BRIDGE_WITH_LEG_EXTENSION",
        WEIGHTED_BRIDGE_WITH_LEG_EXTENSION to "WEIGHTED_BRIDGE_WITH_LEG_EXTENSION",
        CLAM_BRIDGE to "CLAM_BRIDGE",
        FRONT_KICK_TABLETOP to "FRONT_KICK_TABLETOP",
        WEIGHTED_FRONT_KICK_TABLETOP to "WEIGHTED_FRONT_KICK_TABLETOP",
        HIP_EXTENSION_AND_CROSS to "HIP_EXTENSION_AND_CROSS",
        WEIGHTED_HIP_EXTENSION_AND_CROSS to "WEIGHTED_HIP_EXTENSION_AND_CROSS",
        HIP_RAISE to "HIP_RAISE",
        WEIGHTED_HIP_RAISE to "WEIGHTED_HIP_RAISE",
        HIP_RAISE_WITH_FEET_ON_SWISS_BALL to "HIP_RAISE_WITH_FEET_ON_SWISS_BALL",
        WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL to "WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL",
        HIP_RAISE_WITH_HEAD_ON_BOSU_BALL to "HIP_RAISE_WITH_HEAD_ON_BOSU_BALL",
        WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL to "WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL",
        HIP_RAISE_WITH_HEAD_ON_SWISS_BALL to "HIP_RAISE_WITH_HEAD_ON_SWISS_BALL",
        WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL to "WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL",
        HIP_RAISE_WITH_KNEE_SQUEEZE to "HIP_RAISE_WITH_KNEE_SQUEEZE",
        WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE to "WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE",
        INCLINE_REAR_LEG_EXTENSION to "INCLINE_REAR_LEG_EXTENSION",
        WEIGHTED_INCLINE_REAR_LEG_EXTENSION to "WEIGHTED_INCLINE_REAR_LEG_EXTENSION",
        KETTLEBELL_SWING to "KETTLEBELL_SWING",
        MARCHING_HIP_RAISE to "MARCHING_HIP_RAISE",
        WEIGHTED_MARCHING_HIP_RAISE to "WEIGHTED_MARCHING_HIP_RAISE",
        MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL to "MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL",
        WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL to "WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL",
        REVERSE_HIP_RAISE to "REVERSE_HIP_RAISE",
        WEIGHTED_REVERSE_HIP_RAISE to "WEIGHTED_REVERSE_HIP_RAISE",
        SINGLE_LEG_HIP_RAISE to "SINGLE_LEG_HIP_RAISE",
        WEIGHTED_SINGLE_LEG_HIP_RAISE to "WEIGHTED_SINGLE_LEG_HIP_RAISE",
        SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH to "SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH",
        WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH to "WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH",
        SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL to "SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL",
        WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL to "WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL",
        SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER to "SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER",
        WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER to "WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER",
        SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL to "SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL",
        WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL to "WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL",
        SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL to "SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL",
        WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL to "WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL",
        WEIGHTED_CLAM_BRIDGE to "WEIGHTED_CLAM_BRIDGE",
        SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL to "SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL",
        CLAMS to "CLAMS",
        INNER_THIGH_CIRCLES to "INNER_THIGH_CIRCLES",
        INNER_THIGH_SIDE_LIFT to "INNER_THIGH_SIDE_LIFT",
        LEG_CIRCLES to "LEG_CIRCLES",
        LEG_LIFT to "LEG_LIFT",
        LEG_LIFT_IN_EXTERNAL_ROTATION to "LEG_LIFT_IN_EXTERNAL_ROTATION"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
