/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from HyperextensionExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object HyperextensionExerciseName {
    const val BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH: Int = 0
    const val WEIGHTED_BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH: Int = 1
    const val BASE_ROTATIONS: Int = 2
    const val WEIGHTED_BASE_ROTATIONS: Int = 3
    const val BENT_KNEE_REVERSE_HYPEREXTENSION: Int = 4
    const val WEIGHTED_BENT_KNEE_REVERSE_HYPEREXTENSION: Int = 5
    const val HOLLOW_HOLD_AND_ROLL: Int = 6
    const val WEIGHTED_HOLLOW_HOLD_AND_ROLL: Int = 7
    const val KICKS: Int = 8
    const val WEIGHTED_KICKS: Int = 9
    const val KNEE_RAISES: Int = 10
    const val WEIGHTED_KNEE_RAISES: Int = 11
    const val KNEELING_SUPERMAN: Int = 12
    const val WEIGHTED_KNEELING_SUPERMAN: Int = 13
    const val LAT_PULL_DOWN_WITH_ROW: Int = 14
    const val MEDICINE_BALL_DEADLIFT_TO_REACH: Int = 15
    const val ONE_ARM_ONE_LEG_ROW: Int = 16
    const val ONE_ARM_ROW_WITH_BAND: Int = 17
    const val OVERHEAD_LUNGE_WITH_MEDICINE_BALL: Int = 18
    const val PLANK_KNEE_TUCKS: Int = 19
    const val WEIGHTED_PLANK_KNEE_TUCKS: Int = 20
    const val SIDE_STEP: Int = 21
    const val WEIGHTED_SIDE_STEP: Int = 22
    const val SINGLE_LEG_BACK_EXTENSION: Int = 23
    const val WEIGHTED_SINGLE_LEG_BACK_EXTENSION: Int = 24
    const val SPINE_EXTENSION: Int = 25
    const val WEIGHTED_SPINE_EXTENSION: Int = 26
    const val STATIC_BACK_EXTENSION: Int = 27
    const val WEIGHTED_STATIC_BACK_EXTENSION: Int = 28
    const val SUPERMAN_FROM_FLOOR: Int = 29
    const val WEIGHTED_SUPERMAN_FROM_FLOOR: Int = 30
    const val SWISS_BALL_BACK_EXTENSION: Int = 31
    const val WEIGHTED_SWISS_BALL_BACK_EXTENSION: Int = 32
    const val SWISS_BALL_HYPEREXTENSION: Int = 33
    const val WEIGHTED_SWISS_BALL_HYPEREXTENSION: Int = 34
    const val SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT: Int = 35
    const val WEIGHTED_SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT: Int = 36
    const val SUPERMAN_ON_SWISS_BALL: Int = 37
    const val COBRA: Int = 38
    const val SUPINE_FLOOR_BARRE: Int = 39 // Deprecated do not use
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH to "BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH",
        WEIGHTED_BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH to "WEIGHTED_BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH",
        BASE_ROTATIONS to "BASE_ROTATIONS",
        WEIGHTED_BASE_ROTATIONS to "WEIGHTED_BASE_ROTATIONS",
        BENT_KNEE_REVERSE_HYPEREXTENSION to "BENT_KNEE_REVERSE_HYPEREXTENSION",
        WEIGHTED_BENT_KNEE_REVERSE_HYPEREXTENSION to "WEIGHTED_BENT_KNEE_REVERSE_HYPEREXTENSION",
        HOLLOW_HOLD_AND_ROLL to "HOLLOW_HOLD_AND_ROLL",
        WEIGHTED_HOLLOW_HOLD_AND_ROLL to "WEIGHTED_HOLLOW_HOLD_AND_ROLL",
        KICKS to "KICKS",
        WEIGHTED_KICKS to "WEIGHTED_KICKS",
        KNEE_RAISES to "KNEE_RAISES",
        WEIGHTED_KNEE_RAISES to "WEIGHTED_KNEE_RAISES",
        KNEELING_SUPERMAN to "KNEELING_SUPERMAN",
        WEIGHTED_KNEELING_SUPERMAN to "WEIGHTED_KNEELING_SUPERMAN",
        LAT_PULL_DOWN_WITH_ROW to "LAT_PULL_DOWN_WITH_ROW",
        MEDICINE_BALL_DEADLIFT_TO_REACH to "MEDICINE_BALL_DEADLIFT_TO_REACH",
        ONE_ARM_ONE_LEG_ROW to "ONE_ARM_ONE_LEG_ROW",
        ONE_ARM_ROW_WITH_BAND to "ONE_ARM_ROW_WITH_BAND",
        OVERHEAD_LUNGE_WITH_MEDICINE_BALL to "OVERHEAD_LUNGE_WITH_MEDICINE_BALL",
        PLANK_KNEE_TUCKS to "PLANK_KNEE_TUCKS",
        WEIGHTED_PLANK_KNEE_TUCKS to "WEIGHTED_PLANK_KNEE_TUCKS",
        SIDE_STEP to "SIDE_STEP",
        WEIGHTED_SIDE_STEP to "WEIGHTED_SIDE_STEP",
        SINGLE_LEG_BACK_EXTENSION to "SINGLE_LEG_BACK_EXTENSION",
        WEIGHTED_SINGLE_LEG_BACK_EXTENSION to "WEIGHTED_SINGLE_LEG_BACK_EXTENSION",
        SPINE_EXTENSION to "SPINE_EXTENSION",
        WEIGHTED_SPINE_EXTENSION to "WEIGHTED_SPINE_EXTENSION",
        STATIC_BACK_EXTENSION to "STATIC_BACK_EXTENSION",
        WEIGHTED_STATIC_BACK_EXTENSION to "WEIGHTED_STATIC_BACK_EXTENSION",
        SUPERMAN_FROM_FLOOR to "SUPERMAN_FROM_FLOOR",
        WEIGHTED_SUPERMAN_FROM_FLOOR to "WEIGHTED_SUPERMAN_FROM_FLOOR",
        SWISS_BALL_BACK_EXTENSION to "SWISS_BALL_BACK_EXTENSION",
        WEIGHTED_SWISS_BALL_BACK_EXTENSION to "WEIGHTED_SWISS_BALL_BACK_EXTENSION",
        SWISS_BALL_HYPEREXTENSION to "SWISS_BALL_HYPEREXTENSION",
        WEIGHTED_SWISS_BALL_HYPEREXTENSION to "WEIGHTED_SWISS_BALL_HYPEREXTENSION",
        SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT to "SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT",
        WEIGHTED_SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT to "WEIGHTED_SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT",
        SUPERMAN_ON_SWISS_BALL to "SUPERMAN_ON_SWISS_BALL",
        COBRA to "COBRA",
        SUPINE_FLOOR_BARRE to "SUPINE_FLOOR_BARRE"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
