/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from LungeExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object LungeExerciseName {
    const val OVERHEAD_LUNGE: Int = 0
    const val LUNGE_MATRIX: Int = 1
    const val WEIGHTED_LUNGE_MATRIX: Int = 2
    const val ALTERNATING_BARBELL_FORWARD_LUNGE: Int = 3
    const val ALTERNATING_DUMBBELL_LUNGE_WITH_REACH: Int = 4
    const val BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT: Int = 5
    const val BARBELL_BOX_LUNGE: Int = 6
    const val BARBELL_BULGARIAN_SPLIT_SQUAT: Int = 7
    const val BARBELL_CROSSOVER_LUNGE: Int = 8
    const val BARBELL_FRONT_SPLIT_SQUAT: Int = 9
    const val BARBELL_LUNGE: Int = 10
    const val BARBELL_REVERSE_LUNGE: Int = 11
    const val BARBELL_SIDE_LUNGE: Int = 12
    const val BARBELL_SPLIT_SQUAT: Int = 13
    const val CORE_CONTROL_REAR_LUNGE: Int = 14
    const val DIAGONAL_LUNGE: Int = 15
    const val DROP_LUNGE: Int = 16
    const val DUMBBELL_BOX_LUNGE: Int = 17
    const val DUMBBELL_BULGARIAN_SPLIT_SQUAT: Int = 18
    const val DUMBBELL_CROSSOVER_LUNGE: Int = 19
    const val DUMBBELL_DIAGONAL_LUNGE: Int = 20
    const val DUMBBELL_LUNGE: Int = 21
    const val DUMBBELL_LUNGE_AND_ROTATION: Int = 22
    const val DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT: Int = 23
    const val DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS: Int = 24
    const val DUMBBELL_SIDE_LUNGE: Int = 25
    const val ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT: Int = 26
    const val FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT: Int = 27
    const val GUNSLINGER_LUNGE: Int = 28
    const val LAWNMOWER_LUNGE: Int = 29
    const val LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION: Int = 30
    const val LOW_SIDE_TO_SIDE_LUNGE: Int = 31
    const val LUNGE: Int = 32
    const val WEIGHTED_LUNGE: Int = 33
    const val LUNGE_WITH_ARM_REACH: Int = 34
    const val LUNGE_WITH_DIAGONAL_REACH: Int = 35
    const val LUNGE_WITH_SIDE_BEND: Int = 36
    const val OFFSET_DUMBBELL_LUNGE: Int = 37
    const val OFFSET_DUMBBELL_REVERSE_LUNGE: Int = 38
    const val OVERHEAD_BULGARIAN_SPLIT_SQUAT: Int = 39
    const val OVERHEAD_DUMBBELL_REVERSE_LUNGE: Int = 40
    const val OVERHEAD_DUMBBELL_SPLIT_SQUAT: Int = 41
    const val OVERHEAD_LUNGE_WITH_ROTATION: Int = 42
    const val REVERSE_BARBELL_BOX_LUNGE: Int = 43
    const val REVERSE_BOX_LUNGE: Int = 44
    const val REVERSE_DUMBBELL_BOX_LUNGE: Int = 45
    const val REVERSE_DUMBBELL_CROSSOVER_LUNGE: Int = 46
    const val REVERSE_DUMBBELL_DIAGONAL_LUNGE: Int = 47
    const val REVERSE_LUNGE_WITH_REACH_BACK: Int = 48
    const val WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK: Int = 49
    const val REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH: Int = 50
    const val WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH: Int = 51
    const val REVERSE_SLIDING_BOX_LUNGE: Int = 52
    const val WEIGHTED_REVERSE_SLIDING_BOX_LUNGE: Int = 53
    const val REVERSE_SLIDING_LUNGE: Int = 54
    const val WEIGHTED_REVERSE_SLIDING_LUNGE: Int = 55
    const val RUNNERS_LUNGE_TO_BALANCE: Int = 56
    const val WEIGHTED_RUNNERS_LUNGE_TO_BALANCE: Int = 57
    const val SHIFTING_SIDE_LUNGE: Int = 58
    const val SIDE_AND_CROSSOVER_LUNGE: Int = 59
    const val WEIGHTED_SIDE_AND_CROSSOVER_LUNGE: Int = 60
    const val SIDE_LUNGE: Int = 61
    const val WEIGHTED_SIDE_LUNGE: Int = 62
    const val SIDE_LUNGE_AND_PRESS: Int = 63
    const val SIDE_LUNGE_JUMP_OFF: Int = 64
    const val SIDE_LUNGE_SWEEP: Int = 65
    const val WEIGHTED_SIDE_LUNGE_SWEEP: Int = 66
    const val SIDE_LUNGE_TO_CROSSOVER_TAP: Int = 67
    const val WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP: Int = 68
    const val SIDE_TO_SIDE_LUNGE_CHOPS: Int = 69
    const val WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS: Int = 70
    const val SIFF_JUMP_LUNGE: Int = 71
    const val WEIGHTED_SIFF_JUMP_LUNGE: Int = 72
    const val SINGLE_ARM_REVERSE_LUNGE_AND_PRESS: Int = 73
    const val SLIDING_LATERAL_LUNGE: Int = 74
    const val WEIGHTED_SLIDING_LATERAL_LUNGE: Int = 75
    const val WALKING_BARBELL_LUNGE: Int = 76
    const val WALKING_DUMBBELL_LUNGE: Int = 77
    const val WALKING_LUNGE: Int = 78
    const val WEIGHTED_WALKING_LUNGE: Int = 79
    const val WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT: Int = 80
    const val ALTERNATING_DUMBBELL_LUNGE: Int = 81
    const val DUMBBELL_REVERSE_LUNGE: Int = 82
    const val OVERHEAD_DUMBBELL_LUNGE: Int = 83
    const val SCISSOR_POWER_SWITCH: Int = 84
    const val DUMBBELL_OVERHEAD_WALKING_LUNGE: Int = 85
    const val CURTSY_LUNGE: Int = 86
    const val WEIGHTED_CURTSY_LUNGE: Int = 87
    const val WEIGHTED_SHIFTING_SIDE_LUNGE: Int = 88
    const val WEIGHTED_SIDE_LUNGE_AND_PRESS: Int = 89
    const val WEIGHTED_SIDE_LUNGE_JUMP_OFF: Int = 90
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        OVERHEAD_LUNGE to "OVERHEAD_LUNGE",
        LUNGE_MATRIX to "LUNGE_MATRIX",
        WEIGHTED_LUNGE_MATRIX to "WEIGHTED_LUNGE_MATRIX",
        ALTERNATING_BARBELL_FORWARD_LUNGE to "ALTERNATING_BARBELL_FORWARD_LUNGE",
        ALTERNATING_DUMBBELL_LUNGE_WITH_REACH to "ALTERNATING_DUMBBELL_LUNGE_WITH_REACH",
        BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT to "BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT",
        BARBELL_BOX_LUNGE to "BARBELL_BOX_LUNGE",
        BARBELL_BULGARIAN_SPLIT_SQUAT to "BARBELL_BULGARIAN_SPLIT_SQUAT",
        BARBELL_CROSSOVER_LUNGE to "BARBELL_CROSSOVER_LUNGE",
        BARBELL_FRONT_SPLIT_SQUAT to "BARBELL_FRONT_SPLIT_SQUAT",
        BARBELL_LUNGE to "BARBELL_LUNGE",
        BARBELL_REVERSE_LUNGE to "BARBELL_REVERSE_LUNGE",
        BARBELL_SIDE_LUNGE to "BARBELL_SIDE_LUNGE",
        BARBELL_SPLIT_SQUAT to "BARBELL_SPLIT_SQUAT",
        CORE_CONTROL_REAR_LUNGE to "CORE_CONTROL_REAR_LUNGE",
        DIAGONAL_LUNGE to "DIAGONAL_LUNGE",
        DROP_LUNGE to "DROP_LUNGE",
        DUMBBELL_BOX_LUNGE to "DUMBBELL_BOX_LUNGE",
        DUMBBELL_BULGARIAN_SPLIT_SQUAT to "DUMBBELL_BULGARIAN_SPLIT_SQUAT",
        DUMBBELL_CROSSOVER_LUNGE to "DUMBBELL_CROSSOVER_LUNGE",
        DUMBBELL_DIAGONAL_LUNGE to "DUMBBELL_DIAGONAL_LUNGE",
        DUMBBELL_LUNGE to "DUMBBELL_LUNGE",
        DUMBBELL_LUNGE_AND_ROTATION to "DUMBBELL_LUNGE_AND_ROTATION",
        DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT to "DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT",
        DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS to "DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS",
        DUMBBELL_SIDE_LUNGE to "DUMBBELL_SIDE_LUNGE",
        ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT to "ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT",
        FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT to "FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT",
        GUNSLINGER_LUNGE to "GUNSLINGER_LUNGE",
        LAWNMOWER_LUNGE to "LAWNMOWER_LUNGE",
        LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION to "LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION",
        LOW_SIDE_TO_SIDE_LUNGE to "LOW_SIDE_TO_SIDE_LUNGE",
        LUNGE to "LUNGE",
        WEIGHTED_LUNGE to "WEIGHTED_LUNGE",
        LUNGE_WITH_ARM_REACH to "LUNGE_WITH_ARM_REACH",
        LUNGE_WITH_DIAGONAL_REACH to "LUNGE_WITH_DIAGONAL_REACH",
        LUNGE_WITH_SIDE_BEND to "LUNGE_WITH_SIDE_BEND",
        OFFSET_DUMBBELL_LUNGE to "OFFSET_DUMBBELL_LUNGE",
        OFFSET_DUMBBELL_REVERSE_LUNGE to "OFFSET_DUMBBELL_REVERSE_LUNGE",
        OVERHEAD_BULGARIAN_SPLIT_SQUAT to "OVERHEAD_BULGARIAN_SPLIT_SQUAT",
        OVERHEAD_DUMBBELL_REVERSE_LUNGE to "OVERHEAD_DUMBBELL_REVERSE_LUNGE",
        OVERHEAD_DUMBBELL_SPLIT_SQUAT to "OVERHEAD_DUMBBELL_SPLIT_SQUAT",
        OVERHEAD_LUNGE_WITH_ROTATION to "OVERHEAD_LUNGE_WITH_ROTATION",
        REVERSE_BARBELL_BOX_LUNGE to "REVERSE_BARBELL_BOX_LUNGE",
        REVERSE_BOX_LUNGE to "REVERSE_BOX_LUNGE",
        REVERSE_DUMBBELL_BOX_LUNGE to "REVERSE_DUMBBELL_BOX_LUNGE",
        REVERSE_DUMBBELL_CROSSOVER_LUNGE to "REVERSE_DUMBBELL_CROSSOVER_LUNGE",
        REVERSE_DUMBBELL_DIAGONAL_LUNGE to "REVERSE_DUMBBELL_DIAGONAL_LUNGE",
        REVERSE_LUNGE_WITH_REACH_BACK to "REVERSE_LUNGE_WITH_REACH_BACK",
        WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK to "WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK",
        REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH to "REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH",
        WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH to "WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH",
        REVERSE_SLIDING_BOX_LUNGE to "REVERSE_SLIDING_BOX_LUNGE",
        WEIGHTED_REVERSE_SLIDING_BOX_LUNGE to "WEIGHTED_REVERSE_SLIDING_BOX_LUNGE",
        REVERSE_SLIDING_LUNGE to "REVERSE_SLIDING_LUNGE",
        WEIGHTED_REVERSE_SLIDING_LUNGE to "WEIGHTED_REVERSE_SLIDING_LUNGE",
        RUNNERS_LUNGE_TO_BALANCE to "RUNNERS_LUNGE_TO_BALANCE",
        WEIGHTED_RUNNERS_LUNGE_TO_BALANCE to "WEIGHTED_RUNNERS_LUNGE_TO_BALANCE",
        SHIFTING_SIDE_LUNGE to "SHIFTING_SIDE_LUNGE",
        SIDE_AND_CROSSOVER_LUNGE to "SIDE_AND_CROSSOVER_LUNGE",
        WEIGHTED_SIDE_AND_CROSSOVER_LUNGE to "WEIGHTED_SIDE_AND_CROSSOVER_LUNGE",
        SIDE_LUNGE to "SIDE_LUNGE",
        WEIGHTED_SIDE_LUNGE to "WEIGHTED_SIDE_LUNGE",
        SIDE_LUNGE_AND_PRESS to "SIDE_LUNGE_AND_PRESS",
        SIDE_LUNGE_JUMP_OFF to "SIDE_LUNGE_JUMP_OFF",
        SIDE_LUNGE_SWEEP to "SIDE_LUNGE_SWEEP",
        WEIGHTED_SIDE_LUNGE_SWEEP to "WEIGHTED_SIDE_LUNGE_SWEEP",
        SIDE_LUNGE_TO_CROSSOVER_TAP to "SIDE_LUNGE_TO_CROSSOVER_TAP",
        WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP to "WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP",
        SIDE_TO_SIDE_LUNGE_CHOPS to "SIDE_TO_SIDE_LUNGE_CHOPS",
        WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS to "WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS",
        SIFF_JUMP_LUNGE to "SIFF_JUMP_LUNGE",
        WEIGHTED_SIFF_JUMP_LUNGE to "WEIGHTED_SIFF_JUMP_LUNGE",
        SINGLE_ARM_REVERSE_LUNGE_AND_PRESS to "SINGLE_ARM_REVERSE_LUNGE_AND_PRESS",
        SLIDING_LATERAL_LUNGE to "SLIDING_LATERAL_LUNGE",
        WEIGHTED_SLIDING_LATERAL_LUNGE to "WEIGHTED_SLIDING_LATERAL_LUNGE",
        WALKING_BARBELL_LUNGE to "WALKING_BARBELL_LUNGE",
        WALKING_DUMBBELL_LUNGE to "WALKING_DUMBBELL_LUNGE",
        WALKING_LUNGE to "WALKING_LUNGE",
        WEIGHTED_WALKING_LUNGE to "WEIGHTED_WALKING_LUNGE",
        WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT to "WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT",
        ALTERNATING_DUMBBELL_LUNGE to "ALTERNATING_DUMBBELL_LUNGE",
        DUMBBELL_REVERSE_LUNGE to "DUMBBELL_REVERSE_LUNGE",
        OVERHEAD_DUMBBELL_LUNGE to "OVERHEAD_DUMBBELL_LUNGE",
        SCISSOR_POWER_SWITCH to "SCISSOR_POWER_SWITCH",
        DUMBBELL_OVERHEAD_WALKING_LUNGE to "DUMBBELL_OVERHEAD_WALKING_LUNGE",
        CURTSY_LUNGE to "CURTSY_LUNGE",
        WEIGHTED_CURTSY_LUNGE to "WEIGHTED_CURTSY_LUNGE",
        WEIGHTED_SHIFTING_SIDE_LUNGE to "WEIGHTED_SHIFTING_SIDE_LUNGE",
        WEIGHTED_SIDE_LUNGE_AND_PRESS to "WEIGHTED_SIDE_LUNGE_AND_PRESS",
        WEIGHTED_SIDE_LUNGE_JUMP_OFF to "WEIGHTED_SIDE_LUNGE_JUMP_OFF"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
