/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from MoveExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object MoveExerciseName {
    const val ARCH_AND_CURL: Int = 0
    const val ARM_CIRCLES_WITH_BALL_BAND_AND_WEIGHT: Int = 1
    const val ARM_STRETCH: Int = 2
    const val BACK_MASSAGE: Int = 3
    const val BELLY_BREATHING: Int = 4
    const val BRIDGE_WITH_BALL: Int = 5
    const val DIAMOND_LEG_CRUNCH: Int = 6
    const val DIAMOND_LEG_LIFT: Int = 7
    const val EIGHT_POINT_SHOULDER_OPENER: Int = 8
    const val FOOT_ROLLING: Int = 9
    const val FOOTWORK: Int = 10
    const val FOOTWORK_ON_DISC: Int = 11
    const val FORWARD_FOLD: Int = 12
    const val FROG_WITH_BAND: Int = 13
    const val HALF_ROLL_UP: Int = 14
    const val HAMSTRING_CURL: Int = 15
    const val HAMSTRING_STRETCH: Int = 16
    const val HIP_STRETCH: Int = 17
    const val HUG_A_TREE_WITH_BALL_BAND_AND_WEIGHT: Int = 18
    const val KNEE_CIRCLES: Int = 19
    const val KNEE_FOLDS_ON_DISC: Int = 20
    const val LATERAL_FLEXION: Int = 21
    const val LEG_STRETCH_WITH_BAND: Int = 22
    const val LEG_STRETCH_WITH_LEG_CIRCLES: Int = 23
    const val LOWER_LIFT_ON_DISC: Int = 24
    const val LUNGE_SQUAT: Int = 25
    const val LUNGES_WITH_KNEE_LIFT: Int = 26
    const val MERMAID_STRETCH: Int = 27
    const val NEUTRAL_PELVIC_POSITION: Int = 28
    const val PELVIC_CLOCKS_ON_DISC: Int = 29
    const val PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS_WITH_CHAIR: Int = 30
    const val PIRIFORMIS_STRETCH: Int = 31
    const val PLANK_KNEE_CROSSES: Int = 32
    const val PLANK_KNEE_PULLS: Int = 33
    const val PLANK_UP_DOWNS: Int = 34
    const val PRAYER_MUDRA: Int = 35
    const val PSOAS_LUNGE_STRETCH: Int = 36
    const val RIBCAGE_BREATHING: Int = 37
    const val ROLL_DOWN: Int = 38
    const val ROLL_UP_WITH_WEIGHT_AND_BAND: Int = 39
    const val SAW: Int = 40
    const val SCAPULAR_STABILIZATION: Int = 41
    const val SCISSORS_ON_DISC: Int = 42
    const val SEATED_HIP_STRETCHUP: Int = 43
    const val SEATED_TWIST: Int = 44
    const val SHAVING_THE_HEAD_WITH_BALL_BAND_AND_WEIGHT: Int = 45
    const val SPINAL_TWIST: Int = 46
    const val SPINAL_TWIST_STRETCH: Int = 47
    const val SPINE_STRETCH_FORWARD: Int = 48
    const val SQUAT_OPEN_ARM_TWIST_POSE: Int = 49
    const val SQUATS_WITH_BALL: Int = 50
    const val STAND_AND_HANG: Int = 51
    const val STANDING_SIDE_STRETCH: Int = 52
    const val STANDING_SINGLE_LEG_FORWARD_BEND_WITH_IT_BAND_OPENER: Int = 53
    const val STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT: Int = 54
    const val STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT_WITH_BALL: Int = 55
    const val STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED: Int = 56
    const val STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED_WITH_BALL: Int = 57
    const val STRAIGHT_LEG_DIAGONAL_CRUNCH: Int = 58
    const val STRAIGHT_LEG_DIAGONAL_CRUNCH_WITH_BALL: Int = 59
    const val TAILBONE_CURL: Int = 60
    const val THROAT_LOCK: Int = 61
    const val TICK_TOCK_SIDE_ROLL: Int = 62
    const val TWIST: Int = 63
    const val V_LEG_CRUNCHES: Int = 64
    const val V_SIT: Int = 65
    const val FORWARD_FOLD_WHEELCHAIR: Int = 66
    const val FORWARD_FOLD_PLUS_WHEELCHAIR: Int = 67
    const val ARM_CIRCLES_LOW_FORWARD_WHEELCHAIR: Int = 68
    const val ARM_CIRCLES_MID_FORWARD_WHEELCHAIR: Int = 69
    const val ARM_CIRCLES_HIGH_FORWARD_WHEELCHAIR: Int = 70
    const val ARM_CIRCLES_LOW_BACKWARD_WHEELCHAIR: Int = 71
    const val ARM_CIRCLES_MID_BACKWARD_WHEELCHAIR: Int = 72
    const val ARM_CIRCLES_HIGH_BACKWARD_WHEELCHAIR: Int = 73
    const val CORE_TWISTS_WHEELCHAIR: Int = 74
    const val ARM_RAISE_WHEELCHAIR: Int = 75
    const val CHEST_EXPAND_WHEELCHAIR: Int = 76
    const val ARM_EXTEND_WHEELCHAIR: Int = 77
    const val FORWARD_BEND_WHEELCHAIR: Int = 78
    const val TOE_TOUCH_WHEELCHAIR: Int = 79
    const val EXTENDED_TOE_TOUCH_WHEELCHAIR: Int = 80
    const val SEATED_ARM_CIRCLES: Int = 81
    const val TRUNK_ROTATIONS: Int = 82
    const val SEATED_TRUNK_ROTATIONS: Int = 83
    const val TOE_TOUCH: Int = 84
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        ARCH_AND_CURL to "ARCH_AND_CURL",
        ARM_CIRCLES_WITH_BALL_BAND_AND_WEIGHT to "ARM_CIRCLES_WITH_BALL_BAND_AND_WEIGHT",
        ARM_STRETCH to "ARM_STRETCH",
        BACK_MASSAGE to "BACK_MASSAGE",
        BELLY_BREATHING to "BELLY_BREATHING",
        BRIDGE_WITH_BALL to "BRIDGE_WITH_BALL",
        DIAMOND_LEG_CRUNCH to "DIAMOND_LEG_CRUNCH",
        DIAMOND_LEG_LIFT to "DIAMOND_LEG_LIFT",
        EIGHT_POINT_SHOULDER_OPENER to "EIGHT_POINT_SHOULDER_OPENER",
        FOOT_ROLLING to "FOOT_ROLLING",
        FOOTWORK to "FOOTWORK",
        FOOTWORK_ON_DISC to "FOOTWORK_ON_DISC",
        FORWARD_FOLD to "FORWARD_FOLD",
        FROG_WITH_BAND to "FROG_WITH_BAND",
        HALF_ROLL_UP to "HALF_ROLL_UP",
        HAMSTRING_CURL to "HAMSTRING_CURL",
        HAMSTRING_STRETCH to "HAMSTRING_STRETCH",
        HIP_STRETCH to "HIP_STRETCH",
        HUG_A_TREE_WITH_BALL_BAND_AND_WEIGHT to "HUG_A_TREE_WITH_BALL_BAND_AND_WEIGHT",
        KNEE_CIRCLES to "KNEE_CIRCLES",
        KNEE_FOLDS_ON_DISC to "KNEE_FOLDS_ON_DISC",
        LATERAL_FLEXION to "LATERAL_FLEXION",
        LEG_STRETCH_WITH_BAND to "LEG_STRETCH_WITH_BAND",
        LEG_STRETCH_WITH_LEG_CIRCLES to "LEG_STRETCH_WITH_LEG_CIRCLES",
        LOWER_LIFT_ON_DISC to "LOWER_LIFT_ON_DISC",
        LUNGE_SQUAT to "LUNGE_SQUAT",
        LUNGES_WITH_KNEE_LIFT to "LUNGES_WITH_KNEE_LIFT",
        MERMAID_STRETCH to "MERMAID_STRETCH",
        NEUTRAL_PELVIC_POSITION to "NEUTRAL_PELVIC_POSITION",
        PELVIC_CLOCKS_ON_DISC to "PELVIC_CLOCKS_ON_DISC",
        PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS_WITH_CHAIR to "PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS_WITH_CHAIR",
        PIRIFORMIS_STRETCH to "PIRIFORMIS_STRETCH",
        PLANK_KNEE_CROSSES to "PLANK_KNEE_CROSSES",
        PLANK_KNEE_PULLS to "PLANK_KNEE_PULLS",
        PLANK_UP_DOWNS to "PLANK_UP_DOWNS",
        PRAYER_MUDRA to "PRAYER_MUDRA",
        PSOAS_LUNGE_STRETCH to "PSOAS_LUNGE_STRETCH",
        RIBCAGE_BREATHING to "RIBCAGE_BREATHING",
        ROLL_DOWN to "ROLL_DOWN",
        ROLL_UP_WITH_WEIGHT_AND_BAND to "ROLL_UP_WITH_WEIGHT_AND_BAND",
        SAW to "SAW",
        SCAPULAR_STABILIZATION to "SCAPULAR_STABILIZATION",
        SCISSORS_ON_DISC to "SCISSORS_ON_DISC",
        SEATED_HIP_STRETCHUP to "SEATED_HIP_STRETCHUP",
        SEATED_TWIST to "SEATED_TWIST",
        SHAVING_THE_HEAD_WITH_BALL_BAND_AND_WEIGHT to "SHAVING_THE_HEAD_WITH_BALL_BAND_AND_WEIGHT",
        SPINAL_TWIST to "SPINAL_TWIST",
        SPINAL_TWIST_STRETCH to "SPINAL_TWIST_STRETCH",
        SPINE_STRETCH_FORWARD to "SPINE_STRETCH_FORWARD",
        SQUAT_OPEN_ARM_TWIST_POSE to "SQUAT_OPEN_ARM_TWIST_POSE",
        SQUATS_WITH_BALL to "SQUATS_WITH_BALL",
        STAND_AND_HANG to "STAND_AND_HANG",
        STANDING_SIDE_STRETCH to "STANDING_SIDE_STRETCH",
        STANDING_SINGLE_LEG_FORWARD_BEND_WITH_IT_BAND_OPENER to "STANDING_SINGLE_LEG_FORWARD_BEND_WITH_IT_BAND_OPENER",
        STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT to "STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT",
        STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT_WITH_BALL to "STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT_WITH_BALL",
        STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED to "STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED",
        STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED_WITH_BALL to "STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED_WITH_BALL",
        STRAIGHT_LEG_DIAGONAL_CRUNCH to "STRAIGHT_LEG_DIAGONAL_CRUNCH",
        STRAIGHT_LEG_DIAGONAL_CRUNCH_WITH_BALL to "STRAIGHT_LEG_DIAGONAL_CRUNCH_WITH_BALL",
        TAILBONE_CURL to "TAILBONE_CURL",
        THROAT_LOCK to "THROAT_LOCK",
        TICK_TOCK_SIDE_ROLL to "TICK_TOCK_SIDE_ROLL",
        TWIST to "TWIST",
        V_LEG_CRUNCHES to "V_LEG_CRUNCHES",
        V_SIT to "V_SIT",
        FORWARD_FOLD_WHEELCHAIR to "FORWARD_FOLD_WHEELCHAIR",
        FORWARD_FOLD_PLUS_WHEELCHAIR to "FORWARD_FOLD_PLUS_WHEELCHAIR",
        ARM_CIRCLES_LOW_FORWARD_WHEELCHAIR to "ARM_CIRCLES_LOW_FORWARD_WHEELCHAIR",
        ARM_CIRCLES_MID_FORWARD_WHEELCHAIR to "ARM_CIRCLES_MID_FORWARD_WHEELCHAIR",
        ARM_CIRCLES_HIGH_FORWARD_WHEELCHAIR to "ARM_CIRCLES_HIGH_FORWARD_WHEELCHAIR",
        ARM_CIRCLES_LOW_BACKWARD_WHEELCHAIR to "ARM_CIRCLES_LOW_BACKWARD_WHEELCHAIR",
        ARM_CIRCLES_MID_BACKWARD_WHEELCHAIR to "ARM_CIRCLES_MID_BACKWARD_WHEELCHAIR",
        ARM_CIRCLES_HIGH_BACKWARD_WHEELCHAIR to "ARM_CIRCLES_HIGH_BACKWARD_WHEELCHAIR",
        CORE_TWISTS_WHEELCHAIR to "CORE_TWISTS_WHEELCHAIR",
        ARM_RAISE_WHEELCHAIR to "ARM_RAISE_WHEELCHAIR",
        CHEST_EXPAND_WHEELCHAIR to "CHEST_EXPAND_WHEELCHAIR",
        ARM_EXTEND_WHEELCHAIR to "ARM_EXTEND_WHEELCHAIR",
        FORWARD_BEND_WHEELCHAIR to "FORWARD_BEND_WHEELCHAIR",
        TOE_TOUCH_WHEELCHAIR to "TOE_TOUCH_WHEELCHAIR",
        EXTENDED_TOE_TOUCH_WHEELCHAIR to "EXTENDED_TOE_TOUCH_WHEELCHAIR",
        SEATED_ARM_CIRCLES to "SEATED_ARM_CIRCLES",
        TRUNK_ROTATIONS to "TRUNK_ROTATIONS",
        SEATED_TRUNK_ROTATIONS to "SEATED_TRUNK_ROTATIONS",
        TOE_TOUCH to "TOE_TOUCH"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
