/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from PlankExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object PlankExerciseName {
    const val _45_DEGREE_PLANK: Int = 0
    const val WEIGHTED_45_DEGREE_PLANK: Int = 1
    const val _90_DEGREE_STATIC_HOLD: Int = 2
    const val WEIGHTED_90_DEGREE_STATIC_HOLD: Int = 3
    const val BEAR_CRAWL: Int = 4
    const val WEIGHTED_BEAR_CRAWL: Int = 5
    const val CROSS_BODY_MOUNTAIN_CLIMBER: Int = 6
    const val WEIGHTED_CROSS_BODY_MOUNTAIN_CLIMBER: Int = 7
    const val ELBOW_PLANK_PIKE_JACKS: Int = 8
    const val WEIGHTED_ELBOW_PLANK_PIKE_JACKS: Int = 9
    const val ELEVATED_FEET_PLANK: Int = 10
    const val WEIGHTED_ELEVATED_FEET_PLANK: Int = 11
    const val ELEVATOR_ABS: Int = 12
    const val WEIGHTED_ELEVATOR_ABS: Int = 13
    const val EXTENDED_PLANK: Int = 14
    const val WEIGHTED_EXTENDED_PLANK: Int = 15
    const val FULL_PLANK_PASSE_TWIST: Int = 16
    const val WEIGHTED_FULL_PLANK_PASSE_TWIST: Int = 17
    const val INCHING_ELBOW_PLANK: Int = 18
    const val WEIGHTED_INCHING_ELBOW_PLANK: Int = 19
    const val INCHWORM_TO_SIDE_PLANK: Int = 20
    const val WEIGHTED_INCHWORM_TO_SIDE_PLANK: Int = 21
    const val KNEELING_PLANK: Int = 22
    const val WEIGHTED_KNEELING_PLANK: Int = 23
    const val KNEELING_SIDE_PLANK_WITH_LEG_LIFT: Int = 24
    const val WEIGHTED_KNEELING_SIDE_PLANK_WITH_LEG_LIFT: Int = 25
    const val LATERAL_ROLL: Int = 26
    const val WEIGHTED_LATERAL_ROLL: Int = 27
    const val LYING_REVERSE_PLANK: Int = 28
    const val WEIGHTED_LYING_REVERSE_PLANK: Int = 29
    const val MEDICINE_BALL_MOUNTAIN_CLIMBER: Int = 30
    const val WEIGHTED_MEDICINE_BALL_MOUNTAIN_CLIMBER: Int = 31
    const val MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION: Int = 32
    const val WEIGHTED_MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION: Int = 33
    const val MOUNTAIN_CLIMBER: Int = 34
    const val WEIGHTED_MOUNTAIN_CLIMBER: Int = 35
    const val MOUNTAIN_CLIMBER_ON_SLIDING_DISCS: Int = 36
    const val WEIGHTED_MOUNTAIN_CLIMBER_ON_SLIDING_DISCS: Int = 37
    const val MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL: Int = 38
    const val WEIGHTED_MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL: Int = 39
    const val MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH: Int = 40
    const val MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL: Int = 41
    const val WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL: Int = 42
    const val PLANK: Int = 43
    const val PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS: Int = 44
    const val WEIGHTED_PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS: Int = 45
    const val PLANK_KNEE_TWIST: Int = 46
    const val WEIGHTED_PLANK_KNEE_TWIST: Int = 47
    const val PLANK_PIKE_JUMPS: Int = 48
    const val WEIGHTED_PLANK_PIKE_JUMPS: Int = 49
    const val PLANK_PIKES: Int = 50
    const val WEIGHTED_PLANK_PIKES: Int = 51
    const val PLANK_TO_STAND_UP: Int = 52
    const val WEIGHTED_PLANK_TO_STAND_UP: Int = 53
    const val PLANK_WITH_ARM_RAISE: Int = 54
    const val WEIGHTED_PLANK_WITH_ARM_RAISE: Int = 55
    const val PLANK_WITH_KNEE_TO_ELBOW: Int = 56
    const val WEIGHTED_PLANK_WITH_KNEE_TO_ELBOW: Int = 57
    const val PLANK_WITH_OBLIQUE_CRUNCH: Int = 58
    const val WEIGHTED_PLANK_WITH_OBLIQUE_CRUNCH: Int = 59
    const val PLYOMETRIC_SIDE_PLANK: Int = 60
    const val WEIGHTED_PLYOMETRIC_SIDE_PLANK: Int = 61
    const val ROLLING_SIDE_PLANK: Int = 62
    const val WEIGHTED_ROLLING_SIDE_PLANK: Int = 63
    const val SIDE_KICK_PLANK: Int = 64
    const val WEIGHTED_SIDE_KICK_PLANK: Int = 65
    const val SIDE_PLANK: Int = 66
    const val WEIGHTED_SIDE_PLANK: Int = 67
    const val SIDE_PLANK_AND_ROW: Int = 68
    const val WEIGHTED_SIDE_PLANK_AND_ROW: Int = 69
    const val SIDE_PLANK_LIFT: Int = 70
    const val WEIGHTED_SIDE_PLANK_LIFT: Int = 71
    const val SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL: Int = 72
    const val WEIGHTED_SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL: Int = 73
    const val SIDE_PLANK_WITH_FEET_ON_BENCH: Int = 74
    const val WEIGHTED_SIDE_PLANK_WITH_FEET_ON_BENCH: Int = 75
    const val SIDE_PLANK_WITH_KNEE_CIRCLE: Int = 76
    const val WEIGHTED_SIDE_PLANK_WITH_KNEE_CIRCLE: Int = 77
    const val SIDE_PLANK_WITH_KNEE_TUCK: Int = 78
    const val WEIGHTED_SIDE_PLANK_WITH_KNEE_TUCK: Int = 79
    const val SIDE_PLANK_WITH_LEG_LIFT: Int = 80
    const val WEIGHTED_SIDE_PLANK_WITH_LEG_LIFT: Int = 81
    const val SIDE_PLANK_WITH_REACH_UNDER: Int = 82
    const val WEIGHTED_SIDE_PLANK_WITH_REACH_UNDER: Int = 83
    const val SINGLE_LEG_ELEVATED_FEET_PLANK: Int = 84
    const val WEIGHTED_SINGLE_LEG_ELEVATED_FEET_PLANK: Int = 85
    const val SINGLE_LEG_FLEX_AND_EXTEND: Int = 86
    const val WEIGHTED_SINGLE_LEG_FLEX_AND_EXTEND: Int = 87
    const val SINGLE_LEG_SIDE_PLANK: Int = 88
    const val WEIGHTED_SINGLE_LEG_SIDE_PLANK: Int = 89
    const val SPIDERMAN_PLANK: Int = 90
    const val WEIGHTED_SPIDERMAN_PLANK: Int = 91
    const val STRAIGHT_ARM_PLANK: Int = 92
    const val WEIGHTED_STRAIGHT_ARM_PLANK: Int = 93
    const val STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH: Int = 94
    const val WEIGHTED_STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH: Int = 95
    const val SWISS_BALL_PLANK: Int = 96
    const val WEIGHTED_SWISS_BALL_PLANK: Int = 97
    const val SWISS_BALL_PLANK_LEG_LIFT: Int = 98
    const val WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT: Int = 99
    const val SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD: Int = 100
    const val SWISS_BALL_PLANK_WITH_FEET_ON_BENCH: Int = 101
    const val WEIGHTED_SWISS_BALL_PLANK_WITH_FEET_ON_BENCH: Int = 102
    const val SWISS_BALL_PRONE_JACKKNIFE: Int = 103
    const val WEIGHTED_SWISS_BALL_PRONE_JACKKNIFE: Int = 104
    const val SWISS_BALL_SIDE_PLANK: Int = 105
    const val WEIGHTED_SWISS_BALL_SIDE_PLANK: Int = 106
    const val THREE_WAY_PLANK: Int = 107
    const val WEIGHTED_THREE_WAY_PLANK: Int = 108
    const val TOWEL_PLANK_AND_KNEE_IN: Int = 109
    const val WEIGHTED_TOWEL_PLANK_AND_KNEE_IN: Int = 110
    const val T_STABILIZATION: Int = 111
    const val WEIGHTED_T_STABILIZATION: Int = 112
    const val TURKISH_GET_UP_TO_SIDE_PLANK: Int = 113
    const val WEIGHTED_TURKISH_GET_UP_TO_SIDE_PLANK: Int = 114
    const val TWO_POINT_PLANK: Int = 115
    const val WEIGHTED_TWO_POINT_PLANK: Int = 116
    const val WEIGHTED_PLANK: Int = 117
    const val WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT: Int = 118
    const val WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT: Int = 119
    const val WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT: Int = 120
    const val WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT: Int = 121
    const val WIDE_STANCE_PLANK_WITH_LEG_LIFT: Int = 122
    const val WEIGHTED_WIDE_STANCE_PLANK_WITH_LEG_LIFT: Int = 123
    const val WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT: Int = 124
    const val WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH: Int = 125
    const val WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD: Int = 126
    const val WEIGHTED_WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT: Int = 127
    const val PLANK_WITH_FEET_ON_SWISS_BALL: Int = 128
    const val SIDE_PLANK_TO_PLANK_WITH_REACH_UNDER: Int = 129
    const val BRIDGE_WITH_GLUTE_LOWER_LIFT: Int = 130
    const val BRIDGE_ONE_LEG_BRIDGE: Int = 131
    const val PLANK_WITH_ARM_VARIATIONS: Int = 132
    const val PLANK_WITH_LEG_LIFT: Int = 133
    const val REVERSE_PLANK_WITH_LEG_PULL: Int = 134
    const val RING_PLANK_SPRAWLS: Int = 135
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        _45_DEGREE_PLANK to "_45_DEGREE_PLANK",
        WEIGHTED_45_DEGREE_PLANK to "WEIGHTED_45_DEGREE_PLANK",
        _90_DEGREE_STATIC_HOLD to "_90_DEGREE_STATIC_HOLD",
        WEIGHTED_90_DEGREE_STATIC_HOLD to "WEIGHTED_90_DEGREE_STATIC_HOLD",
        BEAR_CRAWL to "BEAR_CRAWL",
        WEIGHTED_BEAR_CRAWL to "WEIGHTED_BEAR_CRAWL",
        CROSS_BODY_MOUNTAIN_CLIMBER to "CROSS_BODY_MOUNTAIN_CLIMBER",
        WEIGHTED_CROSS_BODY_MOUNTAIN_CLIMBER to "WEIGHTED_CROSS_BODY_MOUNTAIN_CLIMBER",
        ELBOW_PLANK_PIKE_JACKS to "ELBOW_PLANK_PIKE_JACKS",
        WEIGHTED_ELBOW_PLANK_PIKE_JACKS to "WEIGHTED_ELBOW_PLANK_PIKE_JACKS",
        ELEVATED_FEET_PLANK to "ELEVATED_FEET_PLANK",
        WEIGHTED_ELEVATED_FEET_PLANK to "WEIGHTED_ELEVATED_FEET_PLANK",
        ELEVATOR_ABS to "ELEVATOR_ABS",
        WEIGHTED_ELEVATOR_ABS to "WEIGHTED_ELEVATOR_ABS",
        EXTENDED_PLANK to "EXTENDED_PLANK",
        WEIGHTED_EXTENDED_PLANK to "WEIGHTED_EXTENDED_PLANK",
        FULL_PLANK_PASSE_TWIST to "FULL_PLANK_PASSE_TWIST",
        WEIGHTED_FULL_PLANK_PASSE_TWIST to "WEIGHTED_FULL_PLANK_PASSE_TWIST",
        INCHING_ELBOW_PLANK to "INCHING_ELBOW_PLANK",
        WEIGHTED_INCHING_ELBOW_PLANK to "WEIGHTED_INCHING_ELBOW_PLANK",
        INCHWORM_TO_SIDE_PLANK to "INCHWORM_TO_SIDE_PLANK",
        WEIGHTED_INCHWORM_TO_SIDE_PLANK to "WEIGHTED_INCHWORM_TO_SIDE_PLANK",
        KNEELING_PLANK to "KNEELING_PLANK",
        WEIGHTED_KNEELING_PLANK to "WEIGHTED_KNEELING_PLANK",
        KNEELING_SIDE_PLANK_WITH_LEG_LIFT to "KNEELING_SIDE_PLANK_WITH_LEG_LIFT",
        WEIGHTED_KNEELING_SIDE_PLANK_WITH_LEG_LIFT to "WEIGHTED_KNEELING_SIDE_PLANK_WITH_LEG_LIFT",
        LATERAL_ROLL to "LATERAL_ROLL",
        WEIGHTED_LATERAL_ROLL to "WEIGHTED_LATERAL_ROLL",
        LYING_REVERSE_PLANK to "LYING_REVERSE_PLANK",
        WEIGHTED_LYING_REVERSE_PLANK to "WEIGHTED_LYING_REVERSE_PLANK",
        MEDICINE_BALL_MOUNTAIN_CLIMBER to "MEDICINE_BALL_MOUNTAIN_CLIMBER",
        WEIGHTED_MEDICINE_BALL_MOUNTAIN_CLIMBER to "WEIGHTED_MEDICINE_BALL_MOUNTAIN_CLIMBER",
        MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION to "MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION",
        WEIGHTED_MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION to "WEIGHTED_MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION",
        MOUNTAIN_CLIMBER to "MOUNTAIN_CLIMBER",
        WEIGHTED_MOUNTAIN_CLIMBER to "WEIGHTED_MOUNTAIN_CLIMBER",
        MOUNTAIN_CLIMBER_ON_SLIDING_DISCS to "MOUNTAIN_CLIMBER_ON_SLIDING_DISCS",
        WEIGHTED_MOUNTAIN_CLIMBER_ON_SLIDING_DISCS to "WEIGHTED_MOUNTAIN_CLIMBER_ON_SLIDING_DISCS",
        MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL to "MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL",
        WEIGHTED_MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL to "WEIGHTED_MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL",
        MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH to "MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH",
        MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL to "MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL",
        WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL to "WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL",
        PLANK to "PLANK",
        PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS to "PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS",
        WEIGHTED_PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS to "WEIGHTED_PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS",
        PLANK_KNEE_TWIST to "PLANK_KNEE_TWIST",
        WEIGHTED_PLANK_KNEE_TWIST to "WEIGHTED_PLANK_KNEE_TWIST",
        PLANK_PIKE_JUMPS to "PLANK_PIKE_JUMPS",
        WEIGHTED_PLANK_PIKE_JUMPS to "WEIGHTED_PLANK_PIKE_JUMPS",
        PLANK_PIKES to "PLANK_PIKES",
        WEIGHTED_PLANK_PIKES to "WEIGHTED_PLANK_PIKES",
        PLANK_TO_STAND_UP to "PLANK_TO_STAND_UP",
        WEIGHTED_PLANK_TO_STAND_UP to "WEIGHTED_PLANK_TO_STAND_UP",
        PLANK_WITH_ARM_RAISE to "PLANK_WITH_ARM_RAISE",
        WEIGHTED_PLANK_WITH_ARM_RAISE to "WEIGHTED_PLANK_WITH_ARM_RAISE",
        PLANK_WITH_KNEE_TO_ELBOW to "PLANK_WITH_KNEE_TO_ELBOW",
        WEIGHTED_PLANK_WITH_KNEE_TO_ELBOW to "WEIGHTED_PLANK_WITH_KNEE_TO_ELBOW",
        PLANK_WITH_OBLIQUE_CRUNCH to "PLANK_WITH_OBLIQUE_CRUNCH",
        WEIGHTED_PLANK_WITH_OBLIQUE_CRUNCH to "WEIGHTED_PLANK_WITH_OBLIQUE_CRUNCH",
        PLYOMETRIC_SIDE_PLANK to "PLYOMETRIC_SIDE_PLANK",
        WEIGHTED_PLYOMETRIC_SIDE_PLANK to "WEIGHTED_PLYOMETRIC_SIDE_PLANK",
        ROLLING_SIDE_PLANK to "ROLLING_SIDE_PLANK",
        WEIGHTED_ROLLING_SIDE_PLANK to "WEIGHTED_ROLLING_SIDE_PLANK",
        SIDE_KICK_PLANK to "SIDE_KICK_PLANK",
        WEIGHTED_SIDE_KICK_PLANK to "WEIGHTED_SIDE_KICK_PLANK",
        SIDE_PLANK to "SIDE_PLANK",
        WEIGHTED_SIDE_PLANK to "WEIGHTED_SIDE_PLANK",
        SIDE_PLANK_AND_ROW to "SIDE_PLANK_AND_ROW",
        WEIGHTED_SIDE_PLANK_AND_ROW to "WEIGHTED_SIDE_PLANK_AND_ROW",
        SIDE_PLANK_LIFT to "SIDE_PLANK_LIFT",
        WEIGHTED_SIDE_PLANK_LIFT to "WEIGHTED_SIDE_PLANK_LIFT",
        SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL to "SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL",
        WEIGHTED_SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL to "WEIGHTED_SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL",
        SIDE_PLANK_WITH_FEET_ON_BENCH to "SIDE_PLANK_WITH_FEET_ON_BENCH",
        WEIGHTED_SIDE_PLANK_WITH_FEET_ON_BENCH to "WEIGHTED_SIDE_PLANK_WITH_FEET_ON_BENCH",
        SIDE_PLANK_WITH_KNEE_CIRCLE to "SIDE_PLANK_WITH_KNEE_CIRCLE",
        WEIGHTED_SIDE_PLANK_WITH_KNEE_CIRCLE to "WEIGHTED_SIDE_PLANK_WITH_KNEE_CIRCLE",
        SIDE_PLANK_WITH_KNEE_TUCK to "SIDE_PLANK_WITH_KNEE_TUCK",
        WEIGHTED_SIDE_PLANK_WITH_KNEE_TUCK to "WEIGHTED_SIDE_PLANK_WITH_KNEE_TUCK",
        SIDE_PLANK_WITH_LEG_LIFT to "SIDE_PLANK_WITH_LEG_LIFT",
        WEIGHTED_SIDE_PLANK_WITH_LEG_LIFT to "WEIGHTED_SIDE_PLANK_WITH_LEG_LIFT",
        SIDE_PLANK_WITH_REACH_UNDER to "SIDE_PLANK_WITH_REACH_UNDER",
        WEIGHTED_SIDE_PLANK_WITH_REACH_UNDER to "WEIGHTED_SIDE_PLANK_WITH_REACH_UNDER",
        SINGLE_LEG_ELEVATED_FEET_PLANK to "SINGLE_LEG_ELEVATED_FEET_PLANK",
        WEIGHTED_SINGLE_LEG_ELEVATED_FEET_PLANK to "WEIGHTED_SINGLE_LEG_ELEVATED_FEET_PLANK",
        SINGLE_LEG_FLEX_AND_EXTEND to "SINGLE_LEG_FLEX_AND_EXTEND",
        WEIGHTED_SINGLE_LEG_FLEX_AND_EXTEND to "WEIGHTED_SINGLE_LEG_FLEX_AND_EXTEND",
        SINGLE_LEG_SIDE_PLANK to "SINGLE_LEG_SIDE_PLANK",
        WEIGHTED_SINGLE_LEG_SIDE_PLANK to "WEIGHTED_SINGLE_LEG_SIDE_PLANK",
        SPIDERMAN_PLANK to "SPIDERMAN_PLANK",
        WEIGHTED_SPIDERMAN_PLANK to "WEIGHTED_SPIDERMAN_PLANK",
        STRAIGHT_ARM_PLANK to "STRAIGHT_ARM_PLANK",
        WEIGHTED_STRAIGHT_ARM_PLANK to "WEIGHTED_STRAIGHT_ARM_PLANK",
        STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH to "STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH",
        WEIGHTED_STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH to "WEIGHTED_STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH",
        SWISS_BALL_PLANK to "SWISS_BALL_PLANK",
        WEIGHTED_SWISS_BALL_PLANK to "WEIGHTED_SWISS_BALL_PLANK",
        SWISS_BALL_PLANK_LEG_LIFT to "SWISS_BALL_PLANK_LEG_LIFT",
        WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT to "WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT",
        SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD to "SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD",
        SWISS_BALL_PLANK_WITH_FEET_ON_BENCH to "SWISS_BALL_PLANK_WITH_FEET_ON_BENCH",
        WEIGHTED_SWISS_BALL_PLANK_WITH_FEET_ON_BENCH to "WEIGHTED_SWISS_BALL_PLANK_WITH_FEET_ON_BENCH",
        SWISS_BALL_PRONE_JACKKNIFE to "SWISS_BALL_PRONE_JACKKNIFE",
        WEIGHTED_SWISS_BALL_PRONE_JACKKNIFE to "WEIGHTED_SWISS_BALL_PRONE_JACKKNIFE",
        SWISS_BALL_SIDE_PLANK to "SWISS_BALL_SIDE_PLANK",
        WEIGHTED_SWISS_BALL_SIDE_PLANK to "WEIGHTED_SWISS_BALL_SIDE_PLANK",
        THREE_WAY_PLANK to "THREE_WAY_PLANK",
        WEIGHTED_THREE_WAY_PLANK to "WEIGHTED_THREE_WAY_PLANK",
        TOWEL_PLANK_AND_KNEE_IN to "TOWEL_PLANK_AND_KNEE_IN",
        WEIGHTED_TOWEL_PLANK_AND_KNEE_IN to "WEIGHTED_TOWEL_PLANK_AND_KNEE_IN",
        T_STABILIZATION to "T_STABILIZATION",
        WEIGHTED_T_STABILIZATION to "WEIGHTED_T_STABILIZATION",
        TURKISH_GET_UP_TO_SIDE_PLANK to "TURKISH_GET_UP_TO_SIDE_PLANK",
        WEIGHTED_TURKISH_GET_UP_TO_SIDE_PLANK to "WEIGHTED_TURKISH_GET_UP_TO_SIDE_PLANK",
        TWO_POINT_PLANK to "TWO_POINT_PLANK",
        WEIGHTED_TWO_POINT_PLANK to "WEIGHTED_TWO_POINT_PLANK",
        WEIGHTED_PLANK to "WEIGHTED_PLANK",
        WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT to "WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT",
        WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT to "WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT",
        WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT to "WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT",
        WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT to "WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT",
        WIDE_STANCE_PLANK_WITH_LEG_LIFT to "WIDE_STANCE_PLANK_WITH_LEG_LIFT",
        WEIGHTED_WIDE_STANCE_PLANK_WITH_LEG_LIFT to "WEIGHTED_WIDE_STANCE_PLANK_WITH_LEG_LIFT",
        WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT to "WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT",
        WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH to "WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH",
        WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD to "WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD",
        WEIGHTED_WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT to "WEIGHTED_WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT",
        PLANK_WITH_FEET_ON_SWISS_BALL to "PLANK_WITH_FEET_ON_SWISS_BALL",
        SIDE_PLANK_TO_PLANK_WITH_REACH_UNDER to "SIDE_PLANK_TO_PLANK_WITH_REACH_UNDER",
        BRIDGE_WITH_GLUTE_LOWER_LIFT to "BRIDGE_WITH_GLUTE_LOWER_LIFT",
        BRIDGE_ONE_LEG_BRIDGE to "BRIDGE_ONE_LEG_BRIDGE",
        PLANK_WITH_ARM_VARIATIONS to "PLANK_WITH_ARM_VARIATIONS",
        PLANK_WITH_LEG_LIFT to "PLANK_WITH_LEG_LIFT",
        REVERSE_PLANK_WITH_LEG_PULL to "REVERSE_PLANK_WITH_LEG_PULL",
        RING_PLANK_SPRAWLS to "RING_PLANK_SPRAWLS"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
