/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from PushUpExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object PushUpExerciseName {
    const val CHEST_PRESS_WITH_BAND: Int = 0
    const val ALTERNATING_STAGGERED_PUSH_UP: Int = 1
    const val WEIGHTED_ALTERNATING_STAGGERED_PUSH_UP: Int = 2
    const val ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP: Int = 3
    const val WEIGHTED_ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP: Int = 4
    const val BOSU_BALL_PUSH_UP: Int = 5
    const val WEIGHTED_BOSU_BALL_PUSH_UP: Int = 6
    const val CLAPPING_PUSH_UP: Int = 7
    const val WEIGHTED_CLAPPING_PUSH_UP: Int = 8
    const val CLOSE_GRIP_MEDICINE_BALL_PUSH_UP: Int = 9
    const val WEIGHTED_CLOSE_GRIP_MEDICINE_BALL_PUSH_UP: Int = 10
    const val CLOSE_HANDS_PUSH_UP: Int = 11
    const val WEIGHTED_CLOSE_HANDS_PUSH_UP: Int = 12
    const val DECLINE_PUSH_UP: Int = 13
    const val WEIGHTED_DECLINE_PUSH_UP: Int = 14
    const val DIAMOND_PUSH_UP: Int = 15
    const val WEIGHTED_DIAMOND_PUSH_UP: Int = 16
    const val EXPLOSIVE_CROSSOVER_PUSH_UP: Int = 17
    const val WEIGHTED_EXPLOSIVE_CROSSOVER_PUSH_UP: Int = 18
    const val EXPLOSIVE_PUSH_UP: Int = 19
    const val WEIGHTED_EXPLOSIVE_PUSH_UP: Int = 20
    const val FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP: Int = 21
    const val WEIGHTED_FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP: Int = 22
    const val HAND_RELEASE_PUSH_UP: Int = 23
    const val WEIGHTED_HAND_RELEASE_PUSH_UP: Int = 24
    const val HANDSTAND_PUSH_UP: Int = 25
    const val WEIGHTED_HANDSTAND_PUSH_UP: Int = 26
    const val INCLINE_PUSH_UP: Int = 27
    const val WEIGHTED_INCLINE_PUSH_UP: Int = 28
    const val ISOMETRIC_EXPLOSIVE_PUSH_UP: Int = 29
    const val WEIGHTED_ISOMETRIC_EXPLOSIVE_PUSH_UP: Int = 30
    const val JUDO_PUSH_UP: Int = 31
    const val WEIGHTED_JUDO_PUSH_UP: Int = 32
    const val KNEELING_PUSH_UP: Int = 33
    const val WEIGHTED_KNEELING_PUSH_UP: Int = 34
    const val MEDICINE_BALL_CHEST_PASS: Int = 35
    const val MEDICINE_BALL_PUSH_UP: Int = 36
    const val WEIGHTED_MEDICINE_BALL_PUSH_UP: Int = 37
    const val ONE_ARM_PUSH_UP: Int = 38
    const val WEIGHTED_ONE_ARM_PUSH_UP: Int = 39
    const val WEIGHTED_PUSH_UP: Int = 40
    const val PUSH_UP_AND_ROW: Int = 41
    const val WEIGHTED_PUSH_UP_AND_ROW: Int = 42
    const val PUSH_UP_PLUS: Int = 43
    const val WEIGHTED_PUSH_UP_PLUS: Int = 44
    const val PUSH_UP_WITH_FEET_ON_SWISS_BALL: Int = 45
    const val WEIGHTED_PUSH_UP_WITH_FEET_ON_SWISS_BALL: Int = 46
    const val PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL: Int = 47
    const val WEIGHTED_PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL: Int = 48
    const val SHOULDER_PUSH_UP: Int = 49
    const val WEIGHTED_SHOULDER_PUSH_UP: Int = 50
    const val SINGLE_ARM_MEDICINE_BALL_PUSH_UP: Int = 51
    const val WEIGHTED_SINGLE_ARM_MEDICINE_BALL_PUSH_UP: Int = 52
    const val SPIDERMAN_PUSH_UP: Int = 53
    const val WEIGHTED_SPIDERMAN_PUSH_UP: Int = 54
    const val STACKED_FEET_PUSH_UP: Int = 55
    const val WEIGHTED_STACKED_FEET_PUSH_UP: Int = 56
    const val STAGGERED_HANDS_PUSH_UP: Int = 57
    const val WEIGHTED_STAGGERED_HANDS_PUSH_UP: Int = 58
    const val SUSPENDED_PUSH_UP: Int = 59
    const val WEIGHTED_SUSPENDED_PUSH_UP: Int = 60
    const val SWISS_BALL_PUSH_UP: Int = 61
    const val WEIGHTED_SWISS_BALL_PUSH_UP: Int = 62
    const val SWISS_BALL_PUSH_UP_PLUS: Int = 63
    const val WEIGHTED_SWISS_BALL_PUSH_UP_PLUS: Int = 64
    const val T_PUSH_UP: Int = 65
    const val WEIGHTED_T_PUSH_UP: Int = 66
    const val TRIPLE_STOP_PUSH_UP: Int = 67
    const val WEIGHTED_TRIPLE_STOP_PUSH_UP: Int = 68
    const val WIDE_HANDS_PUSH_UP: Int = 69
    const val WEIGHTED_WIDE_HANDS_PUSH_UP: Int = 70
    const val PARALLETTE_HANDSTAND_PUSH_UP: Int = 71
    const val WEIGHTED_PARALLETTE_HANDSTAND_PUSH_UP: Int = 72
    const val RING_HANDSTAND_PUSH_UP: Int = 73
    const val WEIGHTED_RING_HANDSTAND_PUSH_UP: Int = 74
    const val RING_PUSH_UP: Int = 75
    const val WEIGHTED_RING_PUSH_UP: Int = 76
    const val PUSH_UP: Int = 77
    const val PILATES_PUSHUP: Int = 78
    const val DYNAMIC_PUSH_UP: Int = 79
    const val KIPPING_HANDSTAND_PUSH_UP: Int = 80
    const val SHOULDER_TAPPING_PUSH_UP: Int = 81
    const val BICEPS_PUSH_UP: Int = 82
    const val HINDU_PUSH_UP: Int = 83
    const val PIKE_PUSH_UP: Int = 84
    const val WIDE_GRIP_PUSH_UP: Int = 85
    const val WEIGHTED_BICEPS_PUSH_UP: Int = 86
    const val WEIGHTED_HINDU_PUSH_UP: Int = 87
    const val WEIGHTED_PIKE_PUSH_UP: Int = 88
    const val KIPPING_PARALLETTE_HANDSTAND_PUSH_UP: Int = 89
    const val WALL_PUSH_UP: Int = 90
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        CHEST_PRESS_WITH_BAND to "CHEST_PRESS_WITH_BAND",
        ALTERNATING_STAGGERED_PUSH_UP to "ALTERNATING_STAGGERED_PUSH_UP",
        WEIGHTED_ALTERNATING_STAGGERED_PUSH_UP to "WEIGHTED_ALTERNATING_STAGGERED_PUSH_UP",
        ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP to "ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP",
        WEIGHTED_ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP to "WEIGHTED_ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP",
        BOSU_BALL_PUSH_UP to "BOSU_BALL_PUSH_UP",
        WEIGHTED_BOSU_BALL_PUSH_UP to "WEIGHTED_BOSU_BALL_PUSH_UP",
        CLAPPING_PUSH_UP to "CLAPPING_PUSH_UP",
        WEIGHTED_CLAPPING_PUSH_UP to "WEIGHTED_CLAPPING_PUSH_UP",
        CLOSE_GRIP_MEDICINE_BALL_PUSH_UP to "CLOSE_GRIP_MEDICINE_BALL_PUSH_UP",
        WEIGHTED_CLOSE_GRIP_MEDICINE_BALL_PUSH_UP to "WEIGHTED_CLOSE_GRIP_MEDICINE_BALL_PUSH_UP",
        CLOSE_HANDS_PUSH_UP to "CLOSE_HANDS_PUSH_UP",
        WEIGHTED_CLOSE_HANDS_PUSH_UP to "WEIGHTED_CLOSE_HANDS_PUSH_UP",
        DECLINE_PUSH_UP to "DECLINE_PUSH_UP",
        WEIGHTED_DECLINE_PUSH_UP to "WEIGHTED_DECLINE_PUSH_UP",
        DIAMOND_PUSH_UP to "DIAMOND_PUSH_UP",
        WEIGHTED_DIAMOND_PUSH_UP to "WEIGHTED_DIAMOND_PUSH_UP",
        EXPLOSIVE_CROSSOVER_PUSH_UP to "EXPLOSIVE_CROSSOVER_PUSH_UP",
        WEIGHTED_EXPLOSIVE_CROSSOVER_PUSH_UP to "WEIGHTED_EXPLOSIVE_CROSSOVER_PUSH_UP",
        EXPLOSIVE_PUSH_UP to "EXPLOSIVE_PUSH_UP",
        WEIGHTED_EXPLOSIVE_PUSH_UP to "WEIGHTED_EXPLOSIVE_PUSH_UP",
        FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP to "FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP",
        WEIGHTED_FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP to "WEIGHTED_FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP",
        HAND_RELEASE_PUSH_UP to "HAND_RELEASE_PUSH_UP",
        WEIGHTED_HAND_RELEASE_PUSH_UP to "WEIGHTED_HAND_RELEASE_PUSH_UP",
        HANDSTAND_PUSH_UP to "HANDSTAND_PUSH_UP",
        WEIGHTED_HANDSTAND_PUSH_UP to "WEIGHTED_HANDSTAND_PUSH_UP",
        INCLINE_PUSH_UP to "INCLINE_PUSH_UP",
        WEIGHTED_INCLINE_PUSH_UP to "WEIGHTED_INCLINE_PUSH_UP",
        ISOMETRIC_EXPLOSIVE_PUSH_UP to "ISOMETRIC_EXPLOSIVE_PUSH_UP",
        WEIGHTED_ISOMETRIC_EXPLOSIVE_PUSH_UP to "WEIGHTED_ISOMETRIC_EXPLOSIVE_PUSH_UP",
        JUDO_PUSH_UP to "JUDO_PUSH_UP",
        WEIGHTED_JUDO_PUSH_UP to "WEIGHTED_JUDO_PUSH_UP",
        KNEELING_PUSH_UP to "KNEELING_PUSH_UP",
        WEIGHTED_KNEELING_PUSH_UP to "WEIGHTED_KNEELING_PUSH_UP",
        MEDICINE_BALL_CHEST_PASS to "MEDICINE_BALL_CHEST_PASS",
        MEDICINE_BALL_PUSH_UP to "MEDICINE_BALL_PUSH_UP",
        WEIGHTED_MEDICINE_BALL_PUSH_UP to "WEIGHTED_MEDICINE_BALL_PUSH_UP",
        ONE_ARM_PUSH_UP to "ONE_ARM_PUSH_UP",
        WEIGHTED_ONE_ARM_PUSH_UP to "WEIGHTED_ONE_ARM_PUSH_UP",
        WEIGHTED_PUSH_UP to "WEIGHTED_PUSH_UP",
        PUSH_UP_AND_ROW to "PUSH_UP_AND_ROW",
        WEIGHTED_PUSH_UP_AND_ROW to "WEIGHTED_PUSH_UP_AND_ROW",
        PUSH_UP_PLUS to "PUSH_UP_PLUS",
        WEIGHTED_PUSH_UP_PLUS to "WEIGHTED_PUSH_UP_PLUS",
        PUSH_UP_WITH_FEET_ON_SWISS_BALL to "PUSH_UP_WITH_FEET_ON_SWISS_BALL",
        WEIGHTED_PUSH_UP_WITH_FEET_ON_SWISS_BALL to "WEIGHTED_PUSH_UP_WITH_FEET_ON_SWISS_BALL",
        PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL to "PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL",
        WEIGHTED_PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL to "WEIGHTED_PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL",
        SHOULDER_PUSH_UP to "SHOULDER_PUSH_UP",
        WEIGHTED_SHOULDER_PUSH_UP to "WEIGHTED_SHOULDER_PUSH_UP",
        SINGLE_ARM_MEDICINE_BALL_PUSH_UP to "SINGLE_ARM_MEDICINE_BALL_PUSH_UP",
        WEIGHTED_SINGLE_ARM_MEDICINE_BALL_PUSH_UP to "WEIGHTED_SINGLE_ARM_MEDICINE_BALL_PUSH_UP",
        SPIDERMAN_PUSH_UP to "SPIDERMAN_PUSH_UP",
        WEIGHTED_SPIDERMAN_PUSH_UP to "WEIGHTED_SPIDERMAN_PUSH_UP",
        STACKED_FEET_PUSH_UP to "STACKED_FEET_PUSH_UP",
        WEIGHTED_STACKED_FEET_PUSH_UP to "WEIGHTED_STACKED_FEET_PUSH_UP",
        STAGGERED_HANDS_PUSH_UP to "STAGGERED_HANDS_PUSH_UP",
        WEIGHTED_STAGGERED_HANDS_PUSH_UP to "WEIGHTED_STAGGERED_HANDS_PUSH_UP",
        SUSPENDED_PUSH_UP to "SUSPENDED_PUSH_UP",
        WEIGHTED_SUSPENDED_PUSH_UP to "WEIGHTED_SUSPENDED_PUSH_UP",
        SWISS_BALL_PUSH_UP to "SWISS_BALL_PUSH_UP",
        WEIGHTED_SWISS_BALL_PUSH_UP to "WEIGHTED_SWISS_BALL_PUSH_UP",
        SWISS_BALL_PUSH_UP_PLUS to "SWISS_BALL_PUSH_UP_PLUS",
        WEIGHTED_SWISS_BALL_PUSH_UP_PLUS to "WEIGHTED_SWISS_BALL_PUSH_UP_PLUS",
        T_PUSH_UP to "T_PUSH_UP",
        WEIGHTED_T_PUSH_UP to "WEIGHTED_T_PUSH_UP",
        TRIPLE_STOP_PUSH_UP to "TRIPLE_STOP_PUSH_UP",
        WEIGHTED_TRIPLE_STOP_PUSH_UP to "WEIGHTED_TRIPLE_STOP_PUSH_UP",
        WIDE_HANDS_PUSH_UP to "WIDE_HANDS_PUSH_UP",
        WEIGHTED_WIDE_HANDS_PUSH_UP to "WEIGHTED_WIDE_HANDS_PUSH_UP",
        PARALLETTE_HANDSTAND_PUSH_UP to "PARALLETTE_HANDSTAND_PUSH_UP",
        WEIGHTED_PARALLETTE_HANDSTAND_PUSH_UP to "WEIGHTED_PARALLETTE_HANDSTAND_PUSH_UP",
        RING_HANDSTAND_PUSH_UP to "RING_HANDSTAND_PUSH_UP",
        WEIGHTED_RING_HANDSTAND_PUSH_UP to "WEIGHTED_RING_HANDSTAND_PUSH_UP",
        RING_PUSH_UP to "RING_PUSH_UP",
        WEIGHTED_RING_PUSH_UP to "WEIGHTED_RING_PUSH_UP",
        PUSH_UP to "PUSH_UP",
        PILATES_PUSHUP to "PILATES_PUSHUP",
        DYNAMIC_PUSH_UP to "DYNAMIC_PUSH_UP",
        KIPPING_HANDSTAND_PUSH_UP to "KIPPING_HANDSTAND_PUSH_UP",
        SHOULDER_TAPPING_PUSH_UP to "SHOULDER_TAPPING_PUSH_UP",
        BICEPS_PUSH_UP to "BICEPS_PUSH_UP",
        HINDU_PUSH_UP to "HINDU_PUSH_UP",
        PIKE_PUSH_UP to "PIKE_PUSH_UP",
        WIDE_GRIP_PUSH_UP to "WIDE_GRIP_PUSH_UP",
        WEIGHTED_BICEPS_PUSH_UP to "WEIGHTED_BICEPS_PUSH_UP",
        WEIGHTED_HINDU_PUSH_UP to "WEIGHTED_HINDU_PUSH_UP",
        WEIGHTED_PIKE_PUSH_UP to "WEIGHTED_PIKE_PUSH_UP",
        KIPPING_PARALLETTE_HANDSTAND_PUSH_UP to "KIPPING_PARALLETTE_HANDSTAND_PUSH_UP",
        WALL_PUSH_UP to "WALL_PUSH_UP"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
