/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from RowExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object RowExerciseName {
    const val BARBELL_STRAIGHT_LEG_DEADLIFT_TO_ROW: Int = 0
    const val CABLE_ROW_STANDING: Int = 1
    const val DUMBBELL_ROW: Int = 2
    const val ELEVATED_FEET_INVERTED_ROW: Int = 3
    const val WEIGHTED_ELEVATED_FEET_INVERTED_ROW: Int = 4
    const val FACE_PULL: Int = 5
    const val FACE_PULL_WITH_EXTERNAL_ROTATION: Int = 6
    const val INVERTED_ROW_WITH_FEET_ON_SWISS_BALL: Int = 7
    const val WEIGHTED_INVERTED_ROW_WITH_FEET_ON_SWISS_BALL: Int = 8
    const val KETTLEBELL_ROW: Int = 9
    const val MODIFIED_INVERTED_ROW: Int = 10
    const val WEIGHTED_MODIFIED_INVERTED_ROW: Int = 11
    const val NEUTRAL_GRIP_ALTERNATING_DUMBBELL_ROW: Int = 12
    const val ONE_ARM_BENT_OVER_ROW: Int = 13
    const val ONE_LEGGED_DUMBBELL_ROW: Int = 14
    const val RENEGADE_ROW: Int = 15
    const val REVERSE_GRIP_BARBELL_ROW: Int = 16
    const val ROPE_HANDLE_CABLE_ROW: Int = 17
    const val SEATED_CABLE_ROW: Int = 18
    const val SEATED_DUMBBELL_ROW: Int = 19
    const val SINGLE_ARM_CABLE_ROW: Int = 20
    const val SINGLE_ARM_CABLE_ROW_AND_ROTATION: Int = 21
    const val SINGLE_ARM_INVERTED_ROW: Int = 22
    const val WEIGHTED_SINGLE_ARM_INVERTED_ROW: Int = 23
    const val SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW: Int = 24
    const val SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW_AND_ROTATION: Int = 25
    const val SUSPENDED_INVERTED_ROW: Int = 26
    const val WEIGHTED_SUSPENDED_INVERTED_ROW: Int = 27
    const val T_BAR_ROW: Int = 28
    const val TOWEL_GRIP_INVERTED_ROW: Int = 29
    const val WEIGHTED_TOWEL_GRIP_INVERTED_ROW: Int = 30
    const val UNDERHAND_GRIP_CABLE_ROW: Int = 31
    const val V_GRIP_CABLE_ROW: Int = 32
    const val WIDE_GRIP_SEATED_CABLE_ROW: Int = 33
    const val ALTERNATING_DUMBBELL_ROW: Int = 34
    const val INVERTED_ROW: Int = 35
    const val ROW: Int = 36
    const val WEIGHTED_ROW: Int = 37
    const val INDOOR_ROW: Int = 38
    const val BANDED_FACE_PULLS: Int = 39
    const val CHEST_SUPPORTED_DUMBBELL_ROW: Int = 40
    const val DECLINE_RING_ROW: Int = 41
    const val ELEVATED_RING_ROW: Int = 42
    const val RDL_BENT_OVER_ROW_WITH_BARBELL_DUMBBELL: Int = 43
    const val RING_ROW: Int = 44
    const val BARBELL_ROW: Int = 45
    const val BENT_OVER_ROW_WITH_BARBELL: Int = 46
    const val BENT_OVER_ROW_WITH_DUMBELL: Int = 47
    const val SEATED_UNDERHAND_GRIP_CABLE_ROW: Int = 48
    const val TRX_INVERTED_ROW: Int = 49
    const val WEIGHTED_INVERTED_ROW: Int = 50
    const val WEIGHTED_TRX_INVERTED_ROW: Int = 51
    const val DUMBBELL_ROW_WHEELCHAIR: Int = 52
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BARBELL_STRAIGHT_LEG_DEADLIFT_TO_ROW to "BARBELL_STRAIGHT_LEG_DEADLIFT_TO_ROW",
        CABLE_ROW_STANDING to "CABLE_ROW_STANDING",
        DUMBBELL_ROW to "DUMBBELL_ROW",
        ELEVATED_FEET_INVERTED_ROW to "ELEVATED_FEET_INVERTED_ROW",
        WEIGHTED_ELEVATED_FEET_INVERTED_ROW to "WEIGHTED_ELEVATED_FEET_INVERTED_ROW",
        FACE_PULL to "FACE_PULL",
        FACE_PULL_WITH_EXTERNAL_ROTATION to "FACE_PULL_WITH_EXTERNAL_ROTATION",
        INVERTED_ROW_WITH_FEET_ON_SWISS_BALL to "INVERTED_ROW_WITH_FEET_ON_SWISS_BALL",
        WEIGHTED_INVERTED_ROW_WITH_FEET_ON_SWISS_BALL to "WEIGHTED_INVERTED_ROW_WITH_FEET_ON_SWISS_BALL",
        KETTLEBELL_ROW to "KETTLEBELL_ROW",
        MODIFIED_INVERTED_ROW to "MODIFIED_INVERTED_ROW",
        WEIGHTED_MODIFIED_INVERTED_ROW to "WEIGHTED_MODIFIED_INVERTED_ROW",
        NEUTRAL_GRIP_ALTERNATING_DUMBBELL_ROW to "NEUTRAL_GRIP_ALTERNATING_DUMBBELL_ROW",
        ONE_ARM_BENT_OVER_ROW to "ONE_ARM_BENT_OVER_ROW",
        ONE_LEGGED_DUMBBELL_ROW to "ONE_LEGGED_DUMBBELL_ROW",
        RENEGADE_ROW to "RENEGADE_ROW",
        REVERSE_GRIP_BARBELL_ROW to "REVERSE_GRIP_BARBELL_ROW",
        ROPE_HANDLE_CABLE_ROW to "ROPE_HANDLE_CABLE_ROW",
        SEATED_CABLE_ROW to "SEATED_CABLE_ROW",
        SEATED_DUMBBELL_ROW to "SEATED_DUMBBELL_ROW",
        SINGLE_ARM_CABLE_ROW to "SINGLE_ARM_CABLE_ROW",
        SINGLE_ARM_CABLE_ROW_AND_ROTATION to "SINGLE_ARM_CABLE_ROW_AND_ROTATION",
        SINGLE_ARM_INVERTED_ROW to "SINGLE_ARM_INVERTED_ROW",
        WEIGHTED_SINGLE_ARM_INVERTED_ROW to "WEIGHTED_SINGLE_ARM_INVERTED_ROW",
        SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW to "SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW",
        SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW_AND_ROTATION to "SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW_AND_ROTATION",
        SUSPENDED_INVERTED_ROW to "SUSPENDED_INVERTED_ROW",
        WEIGHTED_SUSPENDED_INVERTED_ROW to "WEIGHTED_SUSPENDED_INVERTED_ROW",
        T_BAR_ROW to "T_BAR_ROW",
        TOWEL_GRIP_INVERTED_ROW to "TOWEL_GRIP_INVERTED_ROW",
        WEIGHTED_TOWEL_GRIP_INVERTED_ROW to "WEIGHTED_TOWEL_GRIP_INVERTED_ROW",
        UNDERHAND_GRIP_CABLE_ROW to "UNDERHAND_GRIP_CABLE_ROW",
        V_GRIP_CABLE_ROW to "V_GRIP_CABLE_ROW",
        WIDE_GRIP_SEATED_CABLE_ROW to "WIDE_GRIP_SEATED_CABLE_ROW",
        ALTERNATING_DUMBBELL_ROW to "ALTERNATING_DUMBBELL_ROW",
        INVERTED_ROW to "INVERTED_ROW",
        ROW to "ROW",
        WEIGHTED_ROW to "WEIGHTED_ROW",
        INDOOR_ROW to "INDOOR_ROW",
        BANDED_FACE_PULLS to "BANDED_FACE_PULLS",
        CHEST_SUPPORTED_DUMBBELL_ROW to "CHEST_SUPPORTED_DUMBBELL_ROW",
        DECLINE_RING_ROW to "DECLINE_RING_ROW",
        ELEVATED_RING_ROW to "ELEVATED_RING_ROW",
        RDL_BENT_OVER_ROW_WITH_BARBELL_DUMBBELL to "RDL_BENT_OVER_ROW_WITH_BARBELL_DUMBBELL",
        RING_ROW to "RING_ROW",
        BARBELL_ROW to "BARBELL_ROW",
        BENT_OVER_ROW_WITH_BARBELL to "BENT_OVER_ROW_WITH_BARBELL",
        BENT_OVER_ROW_WITH_DUMBELL to "BENT_OVER_ROW_WITH_DUMBELL",
        SEATED_UNDERHAND_GRIP_CABLE_ROW to "SEATED_UNDERHAND_GRIP_CABLE_ROW",
        TRX_INVERTED_ROW to "TRX_INVERTED_ROW",
        WEIGHTED_INVERTED_ROW to "WEIGHTED_INVERTED_ROW",
        WEIGHTED_TRX_INVERTED_ROW to "WEIGHTED_TRX_INVERTED_ROW",
        DUMBBELL_ROW_WHEELCHAIR to "DUMBBELL_ROW_WHEELCHAIR"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
