/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from SquatExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package com.garmin.fit

object SquatExerciseName {
    const val LEG_PRESS: Int = 0
    const val BACK_SQUAT_WITH_BODY_BAR: Int = 1
    const val BACK_SQUATS: Int = 2
    const val WEIGHTED_BACK_SQUATS: Int = 3
    const val BALANCING_SQUAT: Int = 4
    const val WEIGHTED_BALANCING_SQUAT: Int = 5
    const val BARBELL_BACK_SQUAT: Int = 6
    const val BARBELL_BOX_SQUAT: Int = 7
    const val BARBELL_FRONT_SQUAT: Int = 8
    const val BARBELL_HACK_SQUAT: Int = 9
    const val BARBELL_HANG_SQUAT_SNATCH: Int = 10
    const val BARBELL_LATERAL_STEP_UP: Int = 11
    const val BARBELL_QUARTER_SQUAT: Int = 12
    const val BARBELL_SIFF_SQUAT: Int = 13
    const val BARBELL_SQUAT_SNATCH: Int = 14
    const val BARBELL_SQUAT_WITH_HEELS_RAISED: Int = 15
    const val BARBELL_STEPOVER: Int = 16
    const val BARBELL_STEP_UP: Int = 17
    const val BENCH_SQUAT_WITH_ROTATIONAL_CHOP: Int = 18
    const val WEIGHTED_BENCH_SQUAT_WITH_ROTATIONAL_CHOP: Int = 19
    const val BODY_WEIGHT_WALL_SQUAT: Int = 20
    const val WEIGHTED_WALL_SQUAT: Int = 21
    const val BOX_STEP_SQUAT: Int = 22
    const val WEIGHTED_BOX_STEP_SQUAT: Int = 23
    const val BRACED_SQUAT: Int = 24
    const val CROSSED_ARM_BARBELL_FRONT_SQUAT: Int = 25
    const val CROSSOVER_DUMBBELL_STEP_UP: Int = 26
    const val DUMBBELL_FRONT_SQUAT: Int = 27
    const val DUMBBELL_SPLIT_SQUAT: Int = 28
    const val DUMBBELL_SQUAT: Int = 29
    const val DUMBBELL_SQUAT_CLEAN: Int = 30
    const val DUMBBELL_STEPOVER: Int = 31
    const val DUMBBELL_STEP_UP: Int = 32
    const val ELEVATED_SINGLE_LEG_SQUAT: Int = 33
    const val WEIGHTED_ELEVATED_SINGLE_LEG_SQUAT: Int = 34
    const val FIGURE_FOUR_SQUATS: Int = 35
    const val WEIGHTED_FIGURE_FOUR_SQUATS: Int = 36
    const val GOBLET_SQUAT: Int = 37
    const val KETTLEBELL_SQUAT: Int = 38
    const val KETTLEBELL_SWING_OVERHEAD: Int = 39
    const val KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT: Int = 40
    const val LATERAL_DUMBBELL_STEP_UP: Int = 41
    const val ONE_LEGGED_SQUAT: Int = 42
    const val OVERHEAD_DUMBBELL_SQUAT: Int = 43
    const val OVERHEAD_SQUAT: Int = 44
    const val PARTIAL_SINGLE_LEG_SQUAT: Int = 45
    const val WEIGHTED_PARTIAL_SINGLE_LEG_SQUAT: Int = 46
    const val PISTOL_SQUAT: Int = 47
    const val WEIGHTED_PISTOL_SQUAT: Int = 48
    const val PLIE_SLIDES: Int = 49
    const val WEIGHTED_PLIE_SLIDES: Int = 50
    const val PLIE_SQUAT: Int = 51
    const val WEIGHTED_PLIE_SQUAT: Int = 52
    const val PRISONER_SQUAT: Int = 53
    const val WEIGHTED_PRISONER_SQUAT: Int = 54
    const val SINGLE_LEG_BENCH_GET_UP: Int = 55
    const val WEIGHTED_SINGLE_LEG_BENCH_GET_UP: Int = 56
    const val SINGLE_LEG_BENCH_SQUAT: Int = 57
    const val WEIGHTED_SINGLE_LEG_BENCH_SQUAT: Int = 58
    const val SINGLE_LEG_SQUAT_ON_SWISS_BALL: Int = 59
    const val WEIGHTED_SINGLE_LEG_SQUAT_ON_SWISS_BALL: Int = 60
    const val SQUAT: Int = 61
    const val WEIGHTED_SQUAT: Int = 62
    const val SQUATS_WITH_BAND: Int = 63
    const val STAGGERED_SQUAT: Int = 64
    const val WEIGHTED_STAGGERED_SQUAT: Int = 65
    const val STEP_UP: Int = 66
    const val WEIGHTED_STEP_UP: Int = 67
    const val SUITCASE_SQUATS: Int = 68
    const val SUMO_SQUAT: Int = 69
    const val SUMO_SQUAT_SLIDE_IN: Int = 70
    const val WEIGHTED_SUMO_SQUAT_SLIDE_IN: Int = 71
    const val SUMO_SQUAT_TO_HIGH_PULL: Int = 72
    const val SUMO_SQUAT_TO_STAND: Int = 73
    const val WEIGHTED_SUMO_SQUAT_TO_STAND: Int = 74
    const val SUMO_SQUAT_WITH_ROTATION: Int = 75
    const val WEIGHTED_SUMO_SQUAT_WITH_ROTATION: Int = 76
    const val SWISS_BALL_BODY_WEIGHT_WALL_SQUAT: Int = 77
    const val WEIGHTED_SWISS_BALL_WALL_SQUAT: Int = 78
    const val THRUSTERS: Int = 79
    const val UNEVEN_SQUAT: Int = 80
    const val WEIGHTED_UNEVEN_SQUAT: Int = 81
    const val WAIST_SLIMMING_SQUAT: Int = 82
    const val WALL_BALL: Int = 83
    const val WIDE_STANCE_BARBELL_SQUAT: Int = 84
    const val WIDE_STANCE_GOBLET_SQUAT: Int = 85
    const val ZERCHER_SQUAT: Int = 86
    const val KBS_OVERHEAD: Int = 87 // Deprecated do not use
    const val SQUAT_AND_SIDE_KICK: Int = 88
    const val SQUAT_JUMPS_IN_N_OUT: Int = 89
    const val PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS: Int = 90
    const val RELEVE_STRAIGHT_LEG_AND_KNEE_BENT_WITH_ONE_LEG_VARIATION: Int = 91
    const val ALTERNATING_BOX_DUMBBELL_STEP_UPS: Int = 92
    const val DUMBBELL_OVERHEAD_SQUAT_SINGLE_ARM: Int = 93
    const val DUMBBELL_SQUAT_SNATCH: Int = 94
    const val MEDICINE_BALL_SQUAT: Int = 95
    const val WALL_BALL_SQUAT_AND_PRESS: Int = 97
    const val SQUAT_AMERICAN_SWING: Int = 98
    const val AIR_SQUAT: Int = 100
    const val DUMBBELL_THRUSTERS: Int = 101
    const val OVERHEAD_BARBELL_SQUAT: Int = 102
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        LEG_PRESS to "LEG_PRESS",
        BACK_SQUAT_WITH_BODY_BAR to "BACK_SQUAT_WITH_BODY_BAR",
        BACK_SQUATS to "BACK_SQUATS",
        WEIGHTED_BACK_SQUATS to "WEIGHTED_BACK_SQUATS",
        BALANCING_SQUAT to "BALANCING_SQUAT",
        WEIGHTED_BALANCING_SQUAT to "WEIGHTED_BALANCING_SQUAT",
        BARBELL_BACK_SQUAT to "BARBELL_BACK_SQUAT",
        BARBELL_BOX_SQUAT to "BARBELL_BOX_SQUAT",
        BARBELL_FRONT_SQUAT to "BARBELL_FRONT_SQUAT",
        BARBELL_HACK_SQUAT to "BARBELL_HACK_SQUAT",
        BARBELL_HANG_SQUAT_SNATCH to "BARBELL_HANG_SQUAT_SNATCH",
        BARBELL_LATERAL_STEP_UP to "BARBELL_LATERAL_STEP_UP",
        BARBELL_QUARTER_SQUAT to "BARBELL_QUARTER_SQUAT",
        BARBELL_SIFF_SQUAT to "BARBELL_SIFF_SQUAT",
        BARBELL_SQUAT_SNATCH to "BARBELL_SQUAT_SNATCH",
        BARBELL_SQUAT_WITH_HEELS_RAISED to "BARBELL_SQUAT_WITH_HEELS_RAISED",
        BARBELL_STEPOVER to "BARBELL_STEPOVER",
        BARBELL_STEP_UP to "BARBELL_STEP_UP",
        BENCH_SQUAT_WITH_ROTATIONAL_CHOP to "BENCH_SQUAT_WITH_ROTATIONAL_CHOP",
        WEIGHTED_BENCH_SQUAT_WITH_ROTATIONAL_CHOP to "WEIGHTED_BENCH_SQUAT_WITH_ROTATIONAL_CHOP",
        BODY_WEIGHT_WALL_SQUAT to "BODY_WEIGHT_WALL_SQUAT",
        WEIGHTED_WALL_SQUAT to "WEIGHTED_WALL_SQUAT",
        BOX_STEP_SQUAT to "BOX_STEP_SQUAT",
        WEIGHTED_BOX_STEP_SQUAT to "WEIGHTED_BOX_STEP_SQUAT",
        BRACED_SQUAT to "BRACED_SQUAT",
        CROSSED_ARM_BARBELL_FRONT_SQUAT to "CROSSED_ARM_BARBELL_FRONT_SQUAT",
        CROSSOVER_DUMBBELL_STEP_UP to "CROSSOVER_DUMBBELL_STEP_UP",
        DUMBBELL_FRONT_SQUAT to "DUMBBELL_FRONT_SQUAT",
        DUMBBELL_SPLIT_SQUAT to "DUMBBELL_SPLIT_SQUAT",
        DUMBBELL_SQUAT to "DUMBBELL_SQUAT",
        DUMBBELL_SQUAT_CLEAN to "DUMBBELL_SQUAT_CLEAN",
        DUMBBELL_STEPOVER to "DUMBBELL_STEPOVER",
        DUMBBELL_STEP_UP to "DUMBBELL_STEP_UP",
        ELEVATED_SINGLE_LEG_SQUAT to "ELEVATED_SINGLE_LEG_SQUAT",
        WEIGHTED_ELEVATED_SINGLE_LEG_SQUAT to "WEIGHTED_ELEVATED_SINGLE_LEG_SQUAT",
        FIGURE_FOUR_SQUATS to "FIGURE_FOUR_SQUATS",
        WEIGHTED_FIGURE_FOUR_SQUATS to "WEIGHTED_FIGURE_FOUR_SQUATS",
        GOBLET_SQUAT to "GOBLET_SQUAT",
        KETTLEBELL_SQUAT to "KETTLEBELL_SQUAT",
        KETTLEBELL_SWING_OVERHEAD to "KETTLEBELL_SWING_OVERHEAD",
        KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT to "KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT",
        LATERAL_DUMBBELL_STEP_UP to "LATERAL_DUMBBELL_STEP_UP",
        ONE_LEGGED_SQUAT to "ONE_LEGGED_SQUAT",
        OVERHEAD_DUMBBELL_SQUAT to "OVERHEAD_DUMBBELL_SQUAT",
        OVERHEAD_SQUAT to "OVERHEAD_SQUAT",
        PARTIAL_SINGLE_LEG_SQUAT to "PARTIAL_SINGLE_LEG_SQUAT",
        WEIGHTED_PARTIAL_SINGLE_LEG_SQUAT to "WEIGHTED_PARTIAL_SINGLE_LEG_SQUAT",
        PISTOL_SQUAT to "PISTOL_SQUAT",
        WEIGHTED_PISTOL_SQUAT to "WEIGHTED_PISTOL_SQUAT",
        PLIE_SLIDES to "PLIE_SLIDES",
        WEIGHTED_PLIE_SLIDES to "WEIGHTED_PLIE_SLIDES",
        PLIE_SQUAT to "PLIE_SQUAT",
        WEIGHTED_PLIE_SQUAT to "WEIGHTED_PLIE_SQUAT",
        PRISONER_SQUAT to "PRISONER_SQUAT",
        WEIGHTED_PRISONER_SQUAT to "WEIGHTED_PRISONER_SQUAT",
        SINGLE_LEG_BENCH_GET_UP to "SINGLE_LEG_BENCH_GET_UP",
        WEIGHTED_SINGLE_LEG_BENCH_GET_UP to "WEIGHTED_SINGLE_LEG_BENCH_GET_UP",
        SINGLE_LEG_BENCH_SQUAT to "SINGLE_LEG_BENCH_SQUAT",
        WEIGHTED_SINGLE_LEG_BENCH_SQUAT to "WEIGHTED_SINGLE_LEG_BENCH_SQUAT",
        SINGLE_LEG_SQUAT_ON_SWISS_BALL to "SINGLE_LEG_SQUAT_ON_SWISS_BALL",
        WEIGHTED_SINGLE_LEG_SQUAT_ON_SWISS_BALL to "WEIGHTED_SINGLE_LEG_SQUAT_ON_SWISS_BALL",
        SQUAT to "SQUAT",
        WEIGHTED_SQUAT to "WEIGHTED_SQUAT",
        SQUATS_WITH_BAND to "SQUATS_WITH_BAND",
        STAGGERED_SQUAT to "STAGGERED_SQUAT",
        WEIGHTED_STAGGERED_SQUAT to "WEIGHTED_STAGGERED_SQUAT",
        STEP_UP to "STEP_UP",
        WEIGHTED_STEP_UP to "WEIGHTED_STEP_UP",
        SUITCASE_SQUATS to "SUITCASE_SQUATS",
        SUMO_SQUAT to "SUMO_SQUAT",
        SUMO_SQUAT_SLIDE_IN to "SUMO_SQUAT_SLIDE_IN",
        WEIGHTED_SUMO_SQUAT_SLIDE_IN to "WEIGHTED_SUMO_SQUAT_SLIDE_IN",
        SUMO_SQUAT_TO_HIGH_PULL to "SUMO_SQUAT_TO_HIGH_PULL",
        SUMO_SQUAT_TO_STAND to "SUMO_SQUAT_TO_STAND",
        WEIGHTED_SUMO_SQUAT_TO_STAND to "WEIGHTED_SUMO_SQUAT_TO_STAND",
        SUMO_SQUAT_WITH_ROTATION to "SUMO_SQUAT_WITH_ROTATION",
        WEIGHTED_SUMO_SQUAT_WITH_ROTATION to "WEIGHTED_SUMO_SQUAT_WITH_ROTATION",
        SWISS_BALL_BODY_WEIGHT_WALL_SQUAT to "SWISS_BALL_BODY_WEIGHT_WALL_SQUAT",
        WEIGHTED_SWISS_BALL_WALL_SQUAT to "WEIGHTED_SWISS_BALL_WALL_SQUAT",
        THRUSTERS to "THRUSTERS",
        UNEVEN_SQUAT to "UNEVEN_SQUAT",
        WEIGHTED_UNEVEN_SQUAT to "WEIGHTED_UNEVEN_SQUAT",
        WAIST_SLIMMING_SQUAT to "WAIST_SLIMMING_SQUAT",
        WALL_BALL to "WALL_BALL",
        WIDE_STANCE_BARBELL_SQUAT to "WIDE_STANCE_BARBELL_SQUAT",
        WIDE_STANCE_GOBLET_SQUAT to "WIDE_STANCE_GOBLET_SQUAT",
        ZERCHER_SQUAT to "ZERCHER_SQUAT",
        KBS_OVERHEAD to "KBS_OVERHEAD",
        SQUAT_AND_SIDE_KICK to "SQUAT_AND_SIDE_KICK",
        SQUAT_JUMPS_IN_N_OUT to "SQUAT_JUMPS_IN_N_OUT",
        PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS to "PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS",
        RELEVE_STRAIGHT_LEG_AND_KNEE_BENT_WITH_ONE_LEG_VARIATION to "RELEVE_STRAIGHT_LEG_AND_KNEE_BENT_WITH_ONE_LEG_VARIATION",
        ALTERNATING_BOX_DUMBBELL_STEP_UPS to "ALTERNATING_BOX_DUMBBELL_STEP_UPS",
        DUMBBELL_OVERHEAD_SQUAT_SINGLE_ARM to "DUMBBELL_OVERHEAD_SQUAT_SINGLE_ARM",
        DUMBBELL_SQUAT_SNATCH to "DUMBBELL_SQUAT_SNATCH",
        MEDICINE_BALL_SQUAT to "MEDICINE_BALL_SQUAT",
        WALL_BALL_SQUAT_AND_PRESS to "WALL_BALL_SQUAT_AND_PRESS",
        SQUAT_AMERICAN_SWING to "SQUAT_AMERICAN_SWING",
        AIR_SQUAT to "AIR_SQUAT",
        DUMBBELL_THRUSTERS to "DUMBBELL_THRUSTERS",
        OVERHEAD_BARBELL_SQUAT to "OVERHEAD_BARBELL_SQUAT"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
