/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from BenchPressExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object BenchPressExerciseName {
    const val ALTERNATING_DUMBBELL_CHEST_PRESS_ON_SWISS_BALL: Int = 0
    const val BARBELL_BENCH_PRESS: Int = 1
    const val BARBELL_BOARD_BENCH_PRESS: Int = 2
    const val BARBELL_FLOOR_PRESS: Int = 3
    const val CLOSE_GRIP_BARBELL_BENCH_PRESS: Int = 4
    const val DECLINE_DUMBBELL_BENCH_PRESS: Int = 5
    const val DUMBBELL_BENCH_PRESS: Int = 6
    const val DUMBBELL_FLOOR_PRESS: Int = 7
    const val INCLINE_BARBELL_BENCH_PRESS: Int = 8
    const val INCLINE_DUMBBELL_BENCH_PRESS: Int = 9
    const val INCLINE_SMITH_MACHINE_BENCH_PRESS: Int = 10
    const val ISOMETRIC_BARBELL_BENCH_PRESS: Int = 11
    const val KETTLEBELL_CHEST_PRESS: Int = 12
    const val NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS: Int = 13
    const val NEUTRAL_GRIP_DUMBBELL_INCLINE_BENCH_PRESS: Int = 14
    const val ONE_ARM_FLOOR_PRESS: Int = 15
    const val WEIGHTED_ONE_ARM_FLOOR_PRESS: Int = 16
    const val PARTIAL_LOCKOUT: Int = 17
    const val REVERSE_GRIP_BARBELL_BENCH_PRESS: Int = 18
    const val REVERSE_GRIP_INCLINE_BENCH_PRESS: Int = 19
    const val SINGLE_ARM_CABLE_CHEST_PRESS: Int = 20
    const val SINGLE_ARM_DUMBBELL_BENCH_PRESS: Int = 21
    const val SMITH_MACHINE_BENCH_PRESS: Int = 22
    const val SWISS_BALL_DUMBBELL_CHEST_PRESS: Int = 23
    const val TRIPLE_STOP_BARBELL_BENCH_PRESS: Int = 24
    const val WIDE_GRIP_BARBELL_BENCH_PRESS: Int = 25
    const val ALTERNATING_DUMBBELL_CHEST_PRESS: Int = 26
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        ALTERNATING_DUMBBELL_CHEST_PRESS_ON_SWISS_BALL to "ALTERNATING_DUMBBELL_CHEST_PRESS_ON_SWISS_BALL",
        BARBELL_BENCH_PRESS to "BARBELL_BENCH_PRESS",
        BARBELL_BOARD_BENCH_PRESS to "BARBELL_BOARD_BENCH_PRESS",
        BARBELL_FLOOR_PRESS to "BARBELL_FLOOR_PRESS",
        CLOSE_GRIP_BARBELL_BENCH_PRESS to "CLOSE_GRIP_BARBELL_BENCH_PRESS",
        DECLINE_DUMBBELL_BENCH_PRESS to "DECLINE_DUMBBELL_BENCH_PRESS",
        DUMBBELL_BENCH_PRESS to "DUMBBELL_BENCH_PRESS",
        DUMBBELL_FLOOR_PRESS to "DUMBBELL_FLOOR_PRESS",
        INCLINE_BARBELL_BENCH_PRESS to "INCLINE_BARBELL_BENCH_PRESS",
        INCLINE_DUMBBELL_BENCH_PRESS to "INCLINE_DUMBBELL_BENCH_PRESS",
        INCLINE_SMITH_MACHINE_BENCH_PRESS to "INCLINE_SMITH_MACHINE_BENCH_PRESS",
        ISOMETRIC_BARBELL_BENCH_PRESS to "ISOMETRIC_BARBELL_BENCH_PRESS",
        KETTLEBELL_CHEST_PRESS to "KETTLEBELL_CHEST_PRESS",
        NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS to "NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS",
        NEUTRAL_GRIP_DUMBBELL_INCLINE_BENCH_PRESS to "NEUTRAL_GRIP_DUMBBELL_INCLINE_BENCH_PRESS",
        ONE_ARM_FLOOR_PRESS to "ONE_ARM_FLOOR_PRESS",
        WEIGHTED_ONE_ARM_FLOOR_PRESS to "WEIGHTED_ONE_ARM_FLOOR_PRESS",
        PARTIAL_LOCKOUT to "PARTIAL_LOCKOUT",
        REVERSE_GRIP_BARBELL_BENCH_PRESS to "REVERSE_GRIP_BARBELL_BENCH_PRESS",
        REVERSE_GRIP_INCLINE_BENCH_PRESS to "REVERSE_GRIP_INCLINE_BENCH_PRESS",
        SINGLE_ARM_CABLE_CHEST_PRESS to "SINGLE_ARM_CABLE_CHEST_PRESS",
        SINGLE_ARM_DUMBBELL_BENCH_PRESS to "SINGLE_ARM_DUMBBELL_BENCH_PRESS",
        SMITH_MACHINE_BENCH_PRESS to "SMITH_MACHINE_BENCH_PRESS",
        SWISS_BALL_DUMBBELL_CHEST_PRESS to "SWISS_BALL_DUMBBELL_CHEST_PRESS",
        TRIPLE_STOP_BARBELL_BENCH_PRESS to "TRIPLE_STOP_BARBELL_BENCH_PRESS",
        WIDE_GRIP_BARBELL_BENCH_PRESS to "WIDE_GRIP_BARBELL_BENCH_PRESS",
        ALTERNATING_DUMBBELL_CHEST_PRESS to "ALTERNATING_DUMBBELL_CHEST_PRESS"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
