/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from HipStabilityExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object HipStabilityExerciseName {
    const val BAND_SIDE_LYING_LEG_RAISE: Int = 0
    const val DEAD_BUG: Int = 1
    const val WEIGHTED_DEAD_BUG: Int = 2
    const val EXTERNAL_HIP_RAISE: Int = 3
    const val WEIGHTED_EXTERNAL_HIP_RAISE: Int = 4
    const val FIRE_HYDRANT_KICKS: Int = 5
    const val WEIGHTED_FIRE_HYDRANT_KICKS: Int = 6
    const val HIP_CIRCLES: Int = 7
    const val WEIGHTED_HIP_CIRCLES: Int = 8
    const val INNER_THIGH_LIFT: Int = 9
    const val WEIGHTED_INNER_THIGH_LIFT: Int = 10
    const val LATERAL_WALKS_WITH_BAND_AT_ANKLES: Int = 11
    const val PRETZEL_SIDE_KICK: Int = 12
    const val WEIGHTED_PRETZEL_SIDE_KICK: Int = 13
    const val PRONE_HIP_INTERNAL_ROTATION: Int = 14
    const val WEIGHTED_PRONE_HIP_INTERNAL_ROTATION: Int = 15
    const val QUADRUPED: Int = 16
    const val QUADRUPED_HIP_EXTENSION: Int = 17
    const val WEIGHTED_QUADRUPED_HIP_EXTENSION: Int = 18
    const val QUADRUPED_WITH_LEG_LIFT: Int = 19
    const val WEIGHTED_QUADRUPED_WITH_LEG_LIFT: Int = 20
    const val SIDE_LYING_LEG_RAISE: Int = 21
    const val WEIGHTED_SIDE_LYING_LEG_RAISE: Int = 22
    const val SLIDING_HIP_ADDUCTION: Int = 23
    const val WEIGHTED_SLIDING_HIP_ADDUCTION: Int = 24
    const val STANDING_ADDUCTION: Int = 25
    const val WEIGHTED_STANDING_ADDUCTION: Int = 26
    const val STANDING_CABLE_HIP_ABDUCTION: Int = 27
    const val STANDING_HIP_ABDUCTION: Int = 28
    const val WEIGHTED_STANDING_HIP_ABDUCTION: Int = 29
    const val STANDING_REAR_LEG_RAISE: Int = 30
    const val WEIGHTED_STANDING_REAR_LEG_RAISE: Int = 31
    const val SUPINE_HIP_INTERNAL_ROTATION: Int = 32
    const val WEIGHTED_SUPINE_HIP_INTERNAL_ROTATION: Int = 33
    const val LYING_ABDUCTION_STRETCH: Int = 34
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BAND_SIDE_LYING_LEG_RAISE to "BAND_SIDE_LYING_LEG_RAISE",
        DEAD_BUG to "DEAD_BUG",
        WEIGHTED_DEAD_BUG to "WEIGHTED_DEAD_BUG",
        EXTERNAL_HIP_RAISE to "EXTERNAL_HIP_RAISE",
        WEIGHTED_EXTERNAL_HIP_RAISE to "WEIGHTED_EXTERNAL_HIP_RAISE",
        FIRE_HYDRANT_KICKS to "FIRE_HYDRANT_KICKS",
        WEIGHTED_FIRE_HYDRANT_KICKS to "WEIGHTED_FIRE_HYDRANT_KICKS",
        HIP_CIRCLES to "HIP_CIRCLES",
        WEIGHTED_HIP_CIRCLES to "WEIGHTED_HIP_CIRCLES",
        INNER_THIGH_LIFT to "INNER_THIGH_LIFT",
        WEIGHTED_INNER_THIGH_LIFT to "WEIGHTED_INNER_THIGH_LIFT",
        LATERAL_WALKS_WITH_BAND_AT_ANKLES to "LATERAL_WALKS_WITH_BAND_AT_ANKLES",
        PRETZEL_SIDE_KICK to "PRETZEL_SIDE_KICK",
        WEIGHTED_PRETZEL_SIDE_KICK to "WEIGHTED_PRETZEL_SIDE_KICK",
        PRONE_HIP_INTERNAL_ROTATION to "PRONE_HIP_INTERNAL_ROTATION",
        WEIGHTED_PRONE_HIP_INTERNAL_ROTATION to "WEIGHTED_PRONE_HIP_INTERNAL_ROTATION",
        QUADRUPED to "QUADRUPED",
        QUADRUPED_HIP_EXTENSION to "QUADRUPED_HIP_EXTENSION",
        WEIGHTED_QUADRUPED_HIP_EXTENSION to "WEIGHTED_QUADRUPED_HIP_EXTENSION",
        QUADRUPED_WITH_LEG_LIFT to "QUADRUPED_WITH_LEG_LIFT",
        WEIGHTED_QUADRUPED_WITH_LEG_LIFT to "WEIGHTED_QUADRUPED_WITH_LEG_LIFT",
        SIDE_LYING_LEG_RAISE to "SIDE_LYING_LEG_RAISE",
        WEIGHTED_SIDE_LYING_LEG_RAISE to "WEIGHTED_SIDE_LYING_LEG_RAISE",
        SLIDING_HIP_ADDUCTION to "SLIDING_HIP_ADDUCTION",
        WEIGHTED_SLIDING_HIP_ADDUCTION to "WEIGHTED_SLIDING_HIP_ADDUCTION",
        STANDING_ADDUCTION to "STANDING_ADDUCTION",
        WEIGHTED_STANDING_ADDUCTION to "WEIGHTED_STANDING_ADDUCTION",
        STANDING_CABLE_HIP_ABDUCTION to "STANDING_CABLE_HIP_ABDUCTION",
        STANDING_HIP_ABDUCTION to "STANDING_HIP_ABDUCTION",
        WEIGHTED_STANDING_HIP_ABDUCTION to "WEIGHTED_STANDING_HIP_ABDUCTION",
        STANDING_REAR_LEG_RAISE to "STANDING_REAR_LEG_RAISE",
        WEIGHTED_STANDING_REAR_LEG_RAISE to "WEIGHTED_STANDING_REAR_LEG_RAISE",
        SUPINE_HIP_INTERNAL_ROTATION to "SUPINE_HIP_INTERNAL_ROTATION",
        WEIGHTED_SUPINE_HIP_INTERNAL_ROTATION to "WEIGHTED_SUPINE_HIP_INTERNAL_ROTATION",
        LYING_ABDUCTION_STRETCH to "LYING_ABDUCTION_STRETCH"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
