/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from PoseExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object PoseExerciseName {
    const val ALL_FOURS: Int = 0
    const val ANKLE_TO_KNEE: Int = 1
    const val BABY_COBRA: Int = 2
    const val BOAT: Int = 3
    const val BOUND_ANGLE: Int = 4
    const val BOUND_SEATED_SINGLE_LEG_FORWARD_BEND: Int = 5
    const val BOW: Int = 6
    const val BOWED_HALF_MOON: Int = 7
    const val BRIDGE: Int = 8
    const val CAT: Int = 9
    const val CHAIR: Int = 10
    const val CHILDS: Int = 11
    const val CORPSE: Int = 12
    const val COW_FACE: Int = 13
    const val COW: Int = 14
    const val DEVOTIONAL_WARRIOR: Int = 15
    const val DOLPHIN_PLANK: Int = 16
    const val DOLPHIN: Int = 17
    const val DOWN_DOG_KNEE_TO_NOSE: Int = 18
    const val DOWN_DOG_SPLIT: Int = 19
    const val DOWN_DOG_SPLIT_OPEN_HIP_BENT_KNEE: Int = 20
    const val DOWNWARD_FACING_DOG: Int = 21
    const val EAGLE: Int = 22
    const val EASY_SEATED: Int = 23
    const val EXTENDED_PUPPY: Int = 24
    const val EXTENDED_SIDE_ANGLE: Int = 25
    const val FISH: Int = 26
    const val FOUR_LIMBED_STAFF: Int = 27
    const val FULL_SPLIT: Int = 28
    const val GATE: Int = 29
    const val HALF_CHAIR_HALF_ANKLE_TO_KNEE: Int = 30
    const val HALF_MOON: Int = 31
    const val HEAD_TO_KNEE: Int = 32
    const val HERON: Int = 33
    const val HEROS: Int = 34
    const val HIGH_LUNGE: Int = 35
    const val KNEES_CHEST_CHIN: Int = 36
    const val LIZARD: Int = 37
    const val LOCUST: Int = 38
    const val LOW_LUNGE: Int = 39
    const val LOW_LUNGE_TWIST: Int = 40
    const val LOW_LUNGE_WITH_KNEE_DOWN: Int = 41
    const val MERMAID: Int = 42
    const val MOUNTAIN: Int = 43
    const val ONE_LEGGED_DOWNWARD_FACING_POSE_OPEN_HIP_BENT_KNEE: Int = 44
    const val ONE_LEGGED_PIGEON: Int = 45
    const val PEACEFUL_WARRIOR: Int = 46
    const val PLANK: Int = 47
    const val PLOW: Int = 48
    const val RECLINED_HAND_TO_FOOT: Int = 49
    const val REVOLVED_HALF_MOON: Int = 50
    const val REVOLVED_HEAD_TO_KNEE: Int = 51
    const val REVOLVED_TRIANGLE: Int = 52
    const val RUNNERS_LUNGE: Int = 53
    const val SEATED_EASY_SIDE_BEND: Int = 54
    const val SEATED_EASY_TWIST: Int = 55
    const val SEATED_LONG_LEG_FORWARD_BEND: Int = 56
    const val SEATED_WIDE_LEG_FORWARD_BEND: Int = 57
    const val SHOULDER_STAND: Int = 58
    const val SIDE_BOAT: Int = 59
    const val SIDE_PLANK: Int = 60
    const val SPHINX: Int = 61
    const val SQUAT_OPEN_ARM_TWIST: Int = 62
    const val SQUAT_PALM_PRESS: Int = 63
    const val STAFF: Int = 64
    const val STANDING_ARMS_UP: Int = 65
    const val STANDING_FORWARD_BEND_HALFWAY_UP: Int = 66
    const val STANDING_FORWARD_BEND: Int = 67
    const val STANDING_SIDE_OPENER: Int = 68
    const val STANDING_SINGLE_LEG_FORWARD_BEND: Int = 69
    const val STANDING_SPLIT: Int = 70
    const val STANDING_WIDE_LEG_FORWARD_BEND: Int = 71
    const val STANDING_WIDE_LEG_FORWARD_BEND_WITH_TWIST: Int = 72
    const val SUPINE_SPINAL_TWIST: Int = 73
    const val TABLE_TOP: Int = 74
    const val THREAD_THE_NEEDLE: Int = 75
    const val THUNDERBOLT: Int = 76
    const val THUNDERBOLT_POSE_BOTH_SIDES_ARM_STRETCH: Int = 77
    const val TREE: Int = 78
    const val TRIANGLE: Int = 79
    const val UP_DOG: Int = 80
    const val UPWARD_FACING_PLANK: Int = 81
    const val WARRIOR_ONE: Int = 82
    const val WARRIOR_THREE: Int = 83
    const val WARRIOR_TWO: Int = 84
    const val WHEEL: Int = 85
    const val WIDE_SIDE_LUNGE: Int = 86
    const val DEEP_BREATHING_WHEELCHAIR: Int = 87
    const val DEEP_BREATHING_LOW_WHEELCHAIR: Int = 88
    const val DEEP_BREATHING_MID_WHEELCHAIR: Int = 89
    const val DEEP_BREATHING_HIGH_WHEELCHAIR: Int = 90
    const val PRAYER_WHEELCHAIR: Int = 91
    const val OVERHEAD_PRAYER_WHEELCHAIR: Int = 92
    const val CACTUS_WHEELCHAIR: Int = 93
    const val BREATHING_PUNCHES_WHEELCHAIR: Int = 94
    const val BREATHING_PUNCHES_EXTENDED_WHEELCHAIR: Int = 95
    const val BREATHING_PUNCHES_OVERHEAD_WHEELCHAIR: Int = 96
    const val BREATHING_PUNCHES_OVERHEAD_AND_DOWN_WHEELCHAIR: Int = 97
    const val BREATHING_PUNCHES_SIDE_WHEELCHAIR: Int = 98
    const val BREATHING_PUNCHES_EXTENDED_SIDE_WHEELCHAIR: Int = 99
    const val BREATHING_PUNCHES_OVERHEAD_SIDE_WHEELCHAIR: Int = 100
    const val BREATHING_PUNCHES_OVERHEAD_AND_DOWN_SIDE_WHEELCHAIR: Int = 101
    const val LEFT_HAND_BACK_WHEELCHAIR: Int = 102
    const val TRIANGLE_WHEELCHAIR: Int = 103
    const val THREAD_THE_NEEDLE_WHEELCHAIR: Int = 104
    const val NECK_FLEXION_AND_EXTENSION_WHEELCHAIR: Int = 105
    const val NECK_LATERAL_FLEXION_WHEELCHAIR: Int = 106
    const val SPINE_FLEXION_AND_EXTENSION_WHEELCHAIR: Int = 107
    const val SPINE_ROTATION_WHEELCHAIR: Int = 108
    const val SPINE_LATERAL_FLEXION_WHEELCHAIR: Int = 109
    const val ALTERNATIVE_SKIING_WHEELCHAIR: Int = 110
    const val REACH_FORWARD_WHEELCHAIR: Int = 111
    const val WARRIOR_WHEELCHAIR: Int = 112
    const val REVERSE_WARRIOR_WHEELCHAIR: Int = 113
    const val DOWNWARD_FACING_DOG_TO_COBRA: Int = 114
    const val SEATED_CAT_COW: Int = 115
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        ALL_FOURS to "ALL_FOURS",
        ANKLE_TO_KNEE to "ANKLE_TO_KNEE",
        BABY_COBRA to "BABY_COBRA",
        BOAT to "BOAT",
        BOUND_ANGLE to "BOUND_ANGLE",
        BOUND_SEATED_SINGLE_LEG_FORWARD_BEND to "BOUND_SEATED_SINGLE_LEG_FORWARD_BEND",
        BOW to "BOW",
        BOWED_HALF_MOON to "BOWED_HALF_MOON",
        BRIDGE to "BRIDGE",
        CAT to "CAT",
        CHAIR to "CHAIR",
        CHILDS to "CHILDS",
        CORPSE to "CORPSE",
        COW_FACE to "COW_FACE",
        COW to "COW",
        DEVOTIONAL_WARRIOR to "DEVOTIONAL_WARRIOR",
        DOLPHIN_PLANK to "DOLPHIN_PLANK",
        DOLPHIN to "DOLPHIN",
        DOWN_DOG_KNEE_TO_NOSE to "DOWN_DOG_KNEE_TO_NOSE",
        DOWN_DOG_SPLIT to "DOWN_DOG_SPLIT",
        DOWN_DOG_SPLIT_OPEN_HIP_BENT_KNEE to "DOWN_DOG_SPLIT_OPEN_HIP_BENT_KNEE",
        DOWNWARD_FACING_DOG to "DOWNWARD_FACING_DOG",
        EAGLE to "EAGLE",
        EASY_SEATED to "EASY_SEATED",
        EXTENDED_PUPPY to "EXTENDED_PUPPY",
        EXTENDED_SIDE_ANGLE to "EXTENDED_SIDE_ANGLE",
        FISH to "FISH",
        FOUR_LIMBED_STAFF to "FOUR_LIMBED_STAFF",
        FULL_SPLIT to "FULL_SPLIT",
        GATE to "GATE",
        HALF_CHAIR_HALF_ANKLE_TO_KNEE to "HALF_CHAIR_HALF_ANKLE_TO_KNEE",
        HALF_MOON to "HALF_MOON",
        HEAD_TO_KNEE to "HEAD_TO_KNEE",
        HERON to "HERON",
        HEROS to "HEROS",
        HIGH_LUNGE to "HIGH_LUNGE",
        KNEES_CHEST_CHIN to "KNEES_CHEST_CHIN",
        LIZARD to "LIZARD",
        LOCUST to "LOCUST",
        LOW_LUNGE to "LOW_LUNGE",
        LOW_LUNGE_TWIST to "LOW_LUNGE_TWIST",
        LOW_LUNGE_WITH_KNEE_DOWN to "LOW_LUNGE_WITH_KNEE_DOWN",
        MERMAID to "MERMAID",
        MOUNTAIN to "MOUNTAIN",
        ONE_LEGGED_DOWNWARD_FACING_POSE_OPEN_HIP_BENT_KNEE to "ONE_LEGGED_DOWNWARD_FACING_POSE_OPEN_HIP_BENT_KNEE",
        ONE_LEGGED_PIGEON to "ONE_LEGGED_PIGEON",
        PEACEFUL_WARRIOR to "PEACEFUL_WARRIOR",
        PLANK to "PLANK",
        PLOW to "PLOW",
        RECLINED_HAND_TO_FOOT to "RECLINED_HAND_TO_FOOT",
        REVOLVED_HALF_MOON to "REVOLVED_HALF_MOON",
        REVOLVED_HEAD_TO_KNEE to "REVOLVED_HEAD_TO_KNEE",
        REVOLVED_TRIANGLE to "REVOLVED_TRIANGLE",
        RUNNERS_LUNGE to "RUNNERS_LUNGE",
        SEATED_EASY_SIDE_BEND to "SEATED_EASY_SIDE_BEND",
        SEATED_EASY_TWIST to "SEATED_EASY_TWIST",
        SEATED_LONG_LEG_FORWARD_BEND to "SEATED_LONG_LEG_FORWARD_BEND",
        SEATED_WIDE_LEG_FORWARD_BEND to "SEATED_WIDE_LEG_FORWARD_BEND",
        SHOULDER_STAND to "SHOULDER_STAND",
        SIDE_BOAT to "SIDE_BOAT",
        SIDE_PLANK to "SIDE_PLANK",
        SPHINX to "SPHINX",
        SQUAT_OPEN_ARM_TWIST to "SQUAT_OPEN_ARM_TWIST",
        SQUAT_PALM_PRESS to "SQUAT_PALM_PRESS",
        STAFF to "STAFF",
        STANDING_ARMS_UP to "STANDING_ARMS_UP",
        STANDING_FORWARD_BEND_HALFWAY_UP to "STANDING_FORWARD_BEND_HALFWAY_UP",
        STANDING_FORWARD_BEND to "STANDING_FORWARD_BEND",
        STANDING_SIDE_OPENER to "STANDING_SIDE_OPENER",
        STANDING_SINGLE_LEG_FORWARD_BEND to "STANDING_SINGLE_LEG_FORWARD_BEND",
        STANDING_SPLIT to "STANDING_SPLIT",
        STANDING_WIDE_LEG_FORWARD_BEND to "STANDING_WIDE_LEG_FORWARD_BEND",
        STANDING_WIDE_LEG_FORWARD_BEND_WITH_TWIST to "STANDING_WIDE_LEG_FORWARD_BEND_WITH_TWIST",
        SUPINE_SPINAL_TWIST to "SUPINE_SPINAL_TWIST",
        TABLE_TOP to "TABLE_TOP",
        THREAD_THE_NEEDLE to "THREAD_THE_NEEDLE",
        THUNDERBOLT to "THUNDERBOLT",
        THUNDERBOLT_POSE_BOTH_SIDES_ARM_STRETCH to "THUNDERBOLT_POSE_BOTH_SIDES_ARM_STRETCH",
        TREE to "TREE",
        TRIANGLE to "TRIANGLE",
        UP_DOG to "UP_DOG",
        UPWARD_FACING_PLANK to "UPWARD_FACING_PLANK",
        WARRIOR_ONE to "WARRIOR_ONE",
        WARRIOR_THREE to "WARRIOR_THREE",
        WARRIOR_TWO to "WARRIOR_TWO",
        WHEEL to "WHEEL",
        WIDE_SIDE_LUNGE to "WIDE_SIDE_LUNGE",
        DEEP_BREATHING_WHEELCHAIR to "DEEP_BREATHING_WHEELCHAIR",
        DEEP_BREATHING_LOW_WHEELCHAIR to "DEEP_BREATHING_LOW_WHEELCHAIR",
        DEEP_BREATHING_MID_WHEELCHAIR to "DEEP_BREATHING_MID_WHEELCHAIR",
        DEEP_BREATHING_HIGH_WHEELCHAIR to "DEEP_BREATHING_HIGH_WHEELCHAIR",
        PRAYER_WHEELCHAIR to "PRAYER_WHEELCHAIR",
        OVERHEAD_PRAYER_WHEELCHAIR to "OVERHEAD_PRAYER_WHEELCHAIR",
        CACTUS_WHEELCHAIR to "CACTUS_WHEELCHAIR",
        BREATHING_PUNCHES_WHEELCHAIR to "BREATHING_PUNCHES_WHEELCHAIR",
        BREATHING_PUNCHES_EXTENDED_WHEELCHAIR to "BREATHING_PUNCHES_EXTENDED_WHEELCHAIR",
        BREATHING_PUNCHES_OVERHEAD_WHEELCHAIR to "BREATHING_PUNCHES_OVERHEAD_WHEELCHAIR",
        BREATHING_PUNCHES_OVERHEAD_AND_DOWN_WHEELCHAIR to "BREATHING_PUNCHES_OVERHEAD_AND_DOWN_WHEELCHAIR",
        BREATHING_PUNCHES_SIDE_WHEELCHAIR to "BREATHING_PUNCHES_SIDE_WHEELCHAIR",
        BREATHING_PUNCHES_EXTENDED_SIDE_WHEELCHAIR to "BREATHING_PUNCHES_EXTENDED_SIDE_WHEELCHAIR",
        BREATHING_PUNCHES_OVERHEAD_SIDE_WHEELCHAIR to "BREATHING_PUNCHES_OVERHEAD_SIDE_WHEELCHAIR",
        BREATHING_PUNCHES_OVERHEAD_AND_DOWN_SIDE_WHEELCHAIR to "BREATHING_PUNCHES_OVERHEAD_AND_DOWN_SIDE_WHEELCHAIR",
        LEFT_HAND_BACK_WHEELCHAIR to "LEFT_HAND_BACK_WHEELCHAIR",
        TRIANGLE_WHEELCHAIR to "TRIANGLE_WHEELCHAIR",
        THREAD_THE_NEEDLE_WHEELCHAIR to "THREAD_THE_NEEDLE_WHEELCHAIR",
        NECK_FLEXION_AND_EXTENSION_WHEELCHAIR to "NECK_FLEXION_AND_EXTENSION_WHEELCHAIR",
        NECK_LATERAL_FLEXION_WHEELCHAIR to "NECK_LATERAL_FLEXION_WHEELCHAIR",
        SPINE_FLEXION_AND_EXTENSION_WHEELCHAIR to "SPINE_FLEXION_AND_EXTENSION_WHEELCHAIR",
        SPINE_ROTATION_WHEELCHAIR to "SPINE_ROTATION_WHEELCHAIR",
        SPINE_LATERAL_FLEXION_WHEELCHAIR to "SPINE_LATERAL_FLEXION_WHEELCHAIR",
        ALTERNATIVE_SKIING_WHEELCHAIR to "ALTERNATIVE_SKIING_WHEELCHAIR",
        REACH_FORWARD_WHEELCHAIR to "REACH_FORWARD_WHEELCHAIR",
        WARRIOR_WHEELCHAIR to "WARRIOR_WHEELCHAIR",
        REVERSE_WARRIOR_WHEELCHAIR to "REVERSE_WARRIOR_WHEELCHAIR",
        DOWNWARD_FACING_DOG_TO_COBRA to "DOWNWARD_FACING_DOG_TO_COBRA",
        SEATED_CAT_COW to "SEATED_CAT_COW"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
