/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from ShoulderPressExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object ShoulderPressExerciseName {
    const val ALTERNATING_DUMBBELL_SHOULDER_PRESS: Int = 0
    const val ARNOLD_PRESS: Int = 1
    const val BARBELL_FRONT_SQUAT_TO_PUSH_PRESS: Int = 2
    const val BARBELL_PUSH_PRESS: Int = 3
    const val BARBELL_SHOULDER_PRESS: Int = 4
    const val DEAD_CURL_PRESS: Int = 5
    const val DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST: Int = 6
    const val DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS: Int = 7
    const val DUMBBELL_PUSH_PRESS: Int = 8
    const val FLOOR_INVERTED_SHOULDER_PRESS: Int = 9
    const val WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS: Int = 10
    const val INVERTED_SHOULDER_PRESS: Int = 11
    const val WEIGHTED_INVERTED_SHOULDER_PRESS: Int = 12
    const val ONE_ARM_PUSH_PRESS: Int = 13
    const val OVERHEAD_BARBELL_PRESS: Int = 14
    const val OVERHEAD_DUMBBELL_PRESS: Int = 15
    const val SEATED_BARBELL_SHOULDER_PRESS: Int = 16
    const val SEATED_DUMBBELL_SHOULDER_PRESS: Int = 17
    const val SINGLE_ARM_DUMBBELL_SHOULDER_PRESS: Int = 18
    const val SINGLE_ARM_STEP_UP_AND_PRESS: Int = 19
    const val SMITH_MACHINE_OVERHEAD_PRESS: Int = 20
    const val SPLIT_STANCE_HAMMER_CURL_TO_PRESS: Int = 21
    const val SWISS_BALL_DUMBBELL_SHOULDER_PRESS: Int = 22
    const val WEIGHT_PLATE_FRONT_RAISE: Int = 23
    const val DUMBBELL_SHOULDER_PRESS: Int = 24
    const val MILITARY_PRESS: Int = 25
    const val STRICT_PRESS: Int = 27
    const val DUMBBELL_FRONT_RAISE: Int = 28
    const val DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR: Int = 29
    const val ARNOLD_PRESS_WHEELCHAIR: Int = 30
    const val OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR: Int = 31
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        ALTERNATING_DUMBBELL_SHOULDER_PRESS to "ALTERNATING_DUMBBELL_SHOULDER_PRESS",
        ARNOLD_PRESS to "ARNOLD_PRESS",
        BARBELL_FRONT_SQUAT_TO_PUSH_PRESS to "BARBELL_FRONT_SQUAT_TO_PUSH_PRESS",
        BARBELL_PUSH_PRESS to "BARBELL_PUSH_PRESS",
        BARBELL_SHOULDER_PRESS to "BARBELL_SHOULDER_PRESS",
        DEAD_CURL_PRESS to "DEAD_CURL_PRESS",
        DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST to "DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST",
        DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS to "DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS",
        DUMBBELL_PUSH_PRESS to "DUMBBELL_PUSH_PRESS",
        FLOOR_INVERTED_SHOULDER_PRESS to "FLOOR_INVERTED_SHOULDER_PRESS",
        WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS to "WEIGHTED_FLOOR_INVERTED_SHOULDER_PRESS",
        INVERTED_SHOULDER_PRESS to "INVERTED_SHOULDER_PRESS",
        WEIGHTED_INVERTED_SHOULDER_PRESS to "WEIGHTED_INVERTED_SHOULDER_PRESS",
        ONE_ARM_PUSH_PRESS to "ONE_ARM_PUSH_PRESS",
        OVERHEAD_BARBELL_PRESS to "OVERHEAD_BARBELL_PRESS",
        OVERHEAD_DUMBBELL_PRESS to "OVERHEAD_DUMBBELL_PRESS",
        SEATED_BARBELL_SHOULDER_PRESS to "SEATED_BARBELL_SHOULDER_PRESS",
        SEATED_DUMBBELL_SHOULDER_PRESS to "SEATED_DUMBBELL_SHOULDER_PRESS",
        SINGLE_ARM_DUMBBELL_SHOULDER_PRESS to "SINGLE_ARM_DUMBBELL_SHOULDER_PRESS",
        SINGLE_ARM_STEP_UP_AND_PRESS to "SINGLE_ARM_STEP_UP_AND_PRESS",
        SMITH_MACHINE_OVERHEAD_PRESS to "SMITH_MACHINE_OVERHEAD_PRESS",
        SPLIT_STANCE_HAMMER_CURL_TO_PRESS to "SPLIT_STANCE_HAMMER_CURL_TO_PRESS",
        SWISS_BALL_DUMBBELL_SHOULDER_PRESS to "SWISS_BALL_DUMBBELL_SHOULDER_PRESS",
        WEIGHT_PLATE_FRONT_RAISE to "WEIGHT_PLATE_FRONT_RAISE",
        DUMBBELL_SHOULDER_PRESS to "DUMBBELL_SHOULDER_PRESS",
        MILITARY_PRESS to "MILITARY_PRESS",
        STRICT_PRESS to "STRICT_PRESS",
        DUMBBELL_FRONT_RAISE to "DUMBBELL_FRONT_RAISE",
        DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR to "DUMBBELL_CURL_TO_OVERHEAD_PRESS_WHEELCHAIR",
        ARNOLD_PRESS_WHEELCHAIR to "ARNOLD_PRESS_WHEELCHAIR",
        OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR to "OVERHEAD_DUMBBELL_PRESS_WHEELCHAIR"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
