/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from TricepsExtensionExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object TricepsExtensionExerciseName {
    const val BENCH_DIP: Int = 0
    const val WEIGHTED_BENCH_DIP: Int = 1
    const val BODY_WEIGHT_DIP: Int = 2
    const val CABLE_KICKBACK: Int = 3
    const val CABLE_LYING_TRICEPS_EXTENSION: Int = 4
    const val CABLE_OVERHEAD_TRICEPS_EXTENSION: Int = 5
    const val DUMBBELL_KICKBACK: Int = 6
    const val DUMBBELL_LYING_TRICEPS_EXTENSION: Int = 7
    const val EZ_BAR_OVERHEAD_TRICEPS_EXTENSION: Int = 8
    const val INCLINE_DIP: Int = 9
    const val WEIGHTED_INCLINE_DIP: Int = 10
    const val INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION: Int = 11
    const val LYING_DUMBBELL_PULLOVER_TO_EXTENSION: Int = 12
    const val LYING_EZ_BAR_TRICEPS_EXTENSION: Int = 13
    const val LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS: Int = 14
    const val OVERHEAD_DUMBBELL_TRICEPS_EXTENSION: Int = 15
    const val RECLINING_TRICEPS_PRESS: Int = 16
    const val REVERSE_GRIP_PRESSDOWN: Int = 17
    const val REVERSE_GRIP_TRICEPS_PRESSDOWN: Int = 18
    const val ROPE_PRESSDOWN: Int = 19
    const val SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION: Int = 20
    const val SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: Int = 21
    const val SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION: Int = 22
    const val SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION: Int = 23
    const val SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION: Int = 24
    const val SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION: Int = 25
    const val SINGLE_LEG_BENCH_DIP_AND_KICK: Int = 26
    const val WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK: Int = 27
    const val SINGLE_LEG_DIP: Int = 28
    const val WEIGHTED_SINGLE_LEG_DIP: Int = 29
    const val STATIC_LYING_TRICEPS_EXTENSION: Int = 30
    const val SUSPENDED_DIP: Int = 31
    const val WEIGHTED_SUSPENDED_DIP: Int = 32
    const val SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION: Int = 33
    const val SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION: Int = 34
    const val SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION: Int = 35
    const val TABLETOP_DIP: Int = 36
    const val WEIGHTED_TABLETOP_DIP: Int = 37
    const val TRICEPS_EXTENSION_ON_FLOOR: Int = 38
    const val TRICEPS_PRESSDOWN: Int = 39
    const val WEIGHTED_DIP: Int = 40
    const val ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION: Int = 41
    const val TRICEPS_PRESS: Int = 42
    const val DUMBBELL_KICKBACK_WHEELCHAIR: Int = 43
    const val OVERHEAD_DUMBBELL_TRICEPS_EXTENSION_WHEELCHAIR: Int = 44
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        BENCH_DIP to "BENCH_DIP",
        WEIGHTED_BENCH_DIP to "WEIGHTED_BENCH_DIP",
        BODY_WEIGHT_DIP to "BODY_WEIGHT_DIP",
        CABLE_KICKBACK to "CABLE_KICKBACK",
        CABLE_LYING_TRICEPS_EXTENSION to "CABLE_LYING_TRICEPS_EXTENSION",
        CABLE_OVERHEAD_TRICEPS_EXTENSION to "CABLE_OVERHEAD_TRICEPS_EXTENSION",
        DUMBBELL_KICKBACK to "DUMBBELL_KICKBACK",
        DUMBBELL_LYING_TRICEPS_EXTENSION to "DUMBBELL_LYING_TRICEPS_EXTENSION",
        EZ_BAR_OVERHEAD_TRICEPS_EXTENSION to "EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
        INCLINE_DIP to "INCLINE_DIP",
        WEIGHTED_INCLINE_DIP to "WEIGHTED_INCLINE_DIP",
        INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION to "INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION",
        LYING_DUMBBELL_PULLOVER_TO_EXTENSION to "LYING_DUMBBELL_PULLOVER_TO_EXTENSION",
        LYING_EZ_BAR_TRICEPS_EXTENSION to "LYING_EZ_BAR_TRICEPS_EXTENSION",
        LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS to "LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS",
        OVERHEAD_DUMBBELL_TRICEPS_EXTENSION to "OVERHEAD_DUMBBELL_TRICEPS_EXTENSION",
        RECLINING_TRICEPS_PRESS to "RECLINING_TRICEPS_PRESS",
        REVERSE_GRIP_PRESSDOWN to "REVERSE_GRIP_PRESSDOWN",
        REVERSE_GRIP_TRICEPS_PRESSDOWN to "REVERSE_GRIP_TRICEPS_PRESSDOWN",
        ROPE_PRESSDOWN to "ROPE_PRESSDOWN",
        SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION to "SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION",
        SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION to "SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
        SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION to "SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
        SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION to "SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION",
        SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION to "SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION",
        SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION to "SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION",
        SINGLE_LEG_BENCH_DIP_AND_KICK to "SINGLE_LEG_BENCH_DIP_AND_KICK",
        WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK to "WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK",
        SINGLE_LEG_DIP to "SINGLE_LEG_DIP",
        WEIGHTED_SINGLE_LEG_DIP to "WEIGHTED_SINGLE_LEG_DIP",
        STATIC_LYING_TRICEPS_EXTENSION to "STATIC_LYING_TRICEPS_EXTENSION",
        SUSPENDED_DIP to "SUSPENDED_DIP",
        WEIGHTED_SUSPENDED_DIP to "WEIGHTED_SUSPENDED_DIP",
        SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION to "SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION",
        SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION to "SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION",
        SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION to "SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION",
        TABLETOP_DIP to "TABLETOP_DIP",
        WEIGHTED_TABLETOP_DIP to "WEIGHTED_TABLETOP_DIP",
        TRICEPS_EXTENSION_ON_FLOOR to "TRICEPS_EXTENSION_ON_FLOOR",
        TRICEPS_PRESSDOWN to "TRICEPS_PRESSDOWN",
        WEIGHTED_DIP to "WEIGHTED_DIP",
        ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION to "ALTERNATING_DUMBBELL_LYING_TRICEPS_EXTENSION",
        TRICEPS_PRESS to "TRICEPS_PRESS",
        DUMBBELL_KICKBACK_WHEELCHAIR to "DUMBBELL_KICKBACK_WHEELCHAIR",
        OVERHEAD_DUMBBELL_TRICEPS_EXTENSION_WHEELCHAIR to "OVERHEAD_DUMBBELL_TRICEPS_EXTENSION_WHEELCHAIR"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
