/////////////////////////////////////////////////////////////////////////////////////////////
// Converted from WarmUpExerciseName.java (Garmin FIT SDK 21.205.0) by converter/convert.py.
// Do NOT edit: re-run `python3 converter/convert.py` to regenerate.
/////////////////////////////////////////////////////////////////////////////////////////////
package io.github.glandais.fit

object WarmUpExerciseName {
    const val QUADRUPED_ROCKING: Int = 0
    const val NECK_TILTS: Int = 1
    const val ANKLE_CIRCLES: Int = 2
    const val ANKLE_DORSIFLEXION_WITH_BAND: Int = 3
    const val ANKLE_INTERNAL_ROTATION: Int = 4
    const val ARM_CIRCLES: Int = 5
    const val BENT_OVER_REACH_TO_SKY: Int = 6
    const val CAT_CAMEL: Int = 7
    const val ELBOW_TO_FOOT_LUNGE: Int = 8
    const val FORWARD_AND_BACKWARD_LEG_SWINGS: Int = 9
    const val GROINERS: Int = 10
    const val INVERTED_HAMSTRING_STRETCH: Int = 11
    const val LATERAL_DUCK_UNDER: Int = 12
    const val NECK_ROTATIONS: Int = 13
    const val OPPOSITE_ARM_AND_LEG_BALANCE: Int = 14
    const val REACH_ROLL_AND_LIFT: Int = 15
    const val SCORPION: Int = 16 // Deprecated do not use
    const val SHOULDER_CIRCLES: Int = 17
    const val SIDE_TO_SIDE_LEG_SWINGS: Int = 18
    const val SLEEPER_STRETCH: Int = 19
    const val SLIDE_OUT: Int = 20
    const val SWISS_BALL_HIP_CROSSOVER: Int = 21
    const val SWISS_BALL_REACH_ROLL_AND_LIFT: Int = 22
    const val SWISS_BALL_WINDSHIELD_WIPERS: Int = 23
    const val THORACIC_ROTATION: Int = 24
    const val WALKING_HIGH_KICKS: Int = 25
    const val WALKING_HIGH_KNEES: Int = 26
    const val WALKING_KNEE_HUGS: Int = 27
    const val WALKING_LEG_CRADLES: Int = 28
    const val WALKOUT: Int = 29
    const val WALKOUT_FROM_PUSH_UP_POSITION: Int = 30
    const val BICEPS_STRETCH: Int = 31
    const val GLUTES_STRETCH: Int = 32
    const val STANDING_HAMSTRING_STRETCH: Int = 33
    const val STRETCH_90_90: Int = 34
    const val STRETCH_ABS: Int = 35
    const val STRETCH_BUTTERFLY: Int = 36
    const val STRETCH_CALF: Int = 37
    const val STRETCH_CAT_COW: Int = 38
    const val STRETCH_CHILDS_POSE: Int = 39
    const val STRETCH_COBRA: Int = 40
    const val STRETCH_FOREARMS: Int = 41
    const val STRETCH_FORWARD_GLUTES: Int = 42
    const val STRETCH_FRONT_SPLIT: Int = 43
    const val STRETCH_HAMSTRING: Int = 44
    const val STRETCH_HIP_FLEXOR_AND_QUAD: Int = 45
    const val STRETCH_LAT: Int = 46
    const val STRETCH_LEVATOR_SCAPULAE: Int = 47
    const val STRETCH_LUNGE_WITH_SPINAL_TWIST: Int = 48
    const val STRETCH_LUNGING_HIP_FLEXOR: Int = 49
    const val STRETCH_LYING_ABDUCTION: Int = 50
    const val STRETCH_LYING_IT_BAND: Int = 51
    const val STRETCH_LYING_KNEE_TO_CHEST: Int = 52
    const val STRETCH_LYING_PIRIFORMIS: Int = 53
    const val STRETCH_LYING_SPINAL_TWIST: Int = 54
    const val STRETCH_NECK: Int = 55
    const val STRETCH_OBLIQUES: Int = 56
    const val STRETCH_OVER_UNDER_SHOULDER: Int = 57
    const val STRETCH_PECTORAL: Int = 58
    const val STRETCH_PIGEON_POSE: Int = 59
    const val STRETCH_PIRIFORMIS: Int = 60
    const val STRETCH_QUAD: Int = 61
    const val STRETCH_SCORPION: Int = 62
    const val STRETCH_SHOULDER: Int = 63
    const val STRETCH_SIDE: Int = 64
    const val STRETCH_SIDE_LUNGE: Int = 65
    const val STRETCH_SIDE_SPLIT: Int = 66
    const val STRETCH_STANDING_IT_BAND: Int = 67
    const val STRETCH_STRADDLE: Int = 68
    const val STRETCH_TRICEPS: Int = 69
    const val STRETCH_WALL_CHEST_AND_SHOULDER: Int = 70
    const val NECK_ROTATIONS_WHEELCHAIR: Int = 71
    const val HALF_KNEELING_ARM_ROTATION: Int = 72
    const val THREE_WAY_ANKLE_MOBILIZATION: Int = 73
    const val NINETY_NINETY_HIP_SWITCH: Int = 74 // 90_90_hip_switch
    const val ACTIVE_FROG: Int = 75
    const val SHOULDER_SWEEPS: Int = 76
    const val ANKLE_LUNGES: Int = 77
    const val BACK_ROLL_FOAM_ROLLER: Int = 78
    const val BEAR_CRAWL: Int = 79
    const val LATISSIMUS_DORSI_FOAM_ROLL: Int = 80
    const val REVERSE_T_HIP_OPENER: Int = 81
    const val SHOULDER_ROLLS: Int = 82
    const val CHEST_OPENERS: Int = 83
    const val TRICEPS_STRETCH: Int = 84
    const val UPPER_BACK_STRETCH: Int = 85
    const val HIP_CIRCLES: Int = 86
    const val ANKLE_STRETCH: Int = 87
    const val MARCHING_IN_PLACE: Int = 88
    const val TRICEPS_STRETCH_WHEELCHAIR: Int = 89
    const val UPPER_BACK_STRETCH_WHEELCHAIR: Int = 90
    val INVALID: Int = Fit.UINT16_INVALID

    private val stringMap: Map<Int, String> = mapOf(
        QUADRUPED_ROCKING to "QUADRUPED_ROCKING",
        NECK_TILTS to "NECK_TILTS",
        ANKLE_CIRCLES to "ANKLE_CIRCLES",
        ANKLE_DORSIFLEXION_WITH_BAND to "ANKLE_DORSIFLEXION_WITH_BAND",
        ANKLE_INTERNAL_ROTATION to "ANKLE_INTERNAL_ROTATION",
        ARM_CIRCLES to "ARM_CIRCLES",
        BENT_OVER_REACH_TO_SKY to "BENT_OVER_REACH_TO_SKY",
        CAT_CAMEL to "CAT_CAMEL",
        ELBOW_TO_FOOT_LUNGE to "ELBOW_TO_FOOT_LUNGE",
        FORWARD_AND_BACKWARD_LEG_SWINGS to "FORWARD_AND_BACKWARD_LEG_SWINGS",
        GROINERS to "GROINERS",
        INVERTED_HAMSTRING_STRETCH to "INVERTED_HAMSTRING_STRETCH",
        LATERAL_DUCK_UNDER to "LATERAL_DUCK_UNDER",
        NECK_ROTATIONS to "NECK_ROTATIONS",
        OPPOSITE_ARM_AND_LEG_BALANCE to "OPPOSITE_ARM_AND_LEG_BALANCE",
        REACH_ROLL_AND_LIFT to "REACH_ROLL_AND_LIFT",
        SCORPION to "SCORPION",
        SHOULDER_CIRCLES to "SHOULDER_CIRCLES",
        SIDE_TO_SIDE_LEG_SWINGS to "SIDE_TO_SIDE_LEG_SWINGS",
        SLEEPER_STRETCH to "SLEEPER_STRETCH",
        SLIDE_OUT to "SLIDE_OUT",
        SWISS_BALL_HIP_CROSSOVER to "SWISS_BALL_HIP_CROSSOVER",
        SWISS_BALL_REACH_ROLL_AND_LIFT to "SWISS_BALL_REACH_ROLL_AND_LIFT",
        SWISS_BALL_WINDSHIELD_WIPERS to "SWISS_BALL_WINDSHIELD_WIPERS",
        THORACIC_ROTATION to "THORACIC_ROTATION",
        WALKING_HIGH_KICKS to "WALKING_HIGH_KICKS",
        WALKING_HIGH_KNEES to "WALKING_HIGH_KNEES",
        WALKING_KNEE_HUGS to "WALKING_KNEE_HUGS",
        WALKING_LEG_CRADLES to "WALKING_LEG_CRADLES",
        WALKOUT to "WALKOUT",
        WALKOUT_FROM_PUSH_UP_POSITION to "WALKOUT_FROM_PUSH_UP_POSITION",
        BICEPS_STRETCH to "BICEPS_STRETCH",
        GLUTES_STRETCH to "GLUTES_STRETCH",
        STANDING_HAMSTRING_STRETCH to "STANDING_HAMSTRING_STRETCH",
        STRETCH_90_90 to "STRETCH_90_90",
        STRETCH_ABS to "STRETCH_ABS",
        STRETCH_BUTTERFLY to "STRETCH_BUTTERFLY",
        STRETCH_CALF to "STRETCH_CALF",
        STRETCH_CAT_COW to "STRETCH_CAT_COW",
        STRETCH_CHILDS_POSE to "STRETCH_CHILDS_POSE",
        STRETCH_COBRA to "STRETCH_COBRA",
        STRETCH_FOREARMS to "STRETCH_FOREARMS",
        STRETCH_FORWARD_GLUTES to "STRETCH_FORWARD_GLUTES",
        STRETCH_FRONT_SPLIT to "STRETCH_FRONT_SPLIT",
        STRETCH_HAMSTRING to "STRETCH_HAMSTRING",
        STRETCH_HIP_FLEXOR_AND_QUAD to "STRETCH_HIP_FLEXOR_AND_QUAD",
        STRETCH_LAT to "STRETCH_LAT",
        STRETCH_LEVATOR_SCAPULAE to "STRETCH_LEVATOR_SCAPULAE",
        STRETCH_LUNGE_WITH_SPINAL_TWIST to "STRETCH_LUNGE_WITH_SPINAL_TWIST",
        STRETCH_LUNGING_HIP_FLEXOR to "STRETCH_LUNGING_HIP_FLEXOR",
        STRETCH_LYING_ABDUCTION to "STRETCH_LYING_ABDUCTION",
        STRETCH_LYING_IT_BAND to "STRETCH_LYING_IT_BAND",
        STRETCH_LYING_KNEE_TO_CHEST to "STRETCH_LYING_KNEE_TO_CHEST",
        STRETCH_LYING_PIRIFORMIS to "STRETCH_LYING_PIRIFORMIS",
        STRETCH_LYING_SPINAL_TWIST to "STRETCH_LYING_SPINAL_TWIST",
        STRETCH_NECK to "STRETCH_NECK",
        STRETCH_OBLIQUES to "STRETCH_OBLIQUES",
        STRETCH_OVER_UNDER_SHOULDER to "STRETCH_OVER_UNDER_SHOULDER",
        STRETCH_PECTORAL to "STRETCH_PECTORAL",
        STRETCH_PIGEON_POSE to "STRETCH_PIGEON_POSE",
        STRETCH_PIRIFORMIS to "STRETCH_PIRIFORMIS",
        STRETCH_QUAD to "STRETCH_QUAD",
        STRETCH_SCORPION to "STRETCH_SCORPION",
        STRETCH_SHOULDER to "STRETCH_SHOULDER",
        STRETCH_SIDE to "STRETCH_SIDE",
        STRETCH_SIDE_LUNGE to "STRETCH_SIDE_LUNGE",
        STRETCH_SIDE_SPLIT to "STRETCH_SIDE_SPLIT",
        STRETCH_STANDING_IT_BAND to "STRETCH_STANDING_IT_BAND",
        STRETCH_STRADDLE to "STRETCH_STRADDLE",
        STRETCH_TRICEPS to "STRETCH_TRICEPS",
        STRETCH_WALL_CHEST_AND_SHOULDER to "STRETCH_WALL_CHEST_AND_SHOULDER",
        NECK_ROTATIONS_WHEELCHAIR to "NECK_ROTATIONS_WHEELCHAIR",
        HALF_KNEELING_ARM_ROTATION to "HALF_KNEELING_ARM_ROTATION",
        THREE_WAY_ANKLE_MOBILIZATION to "THREE_WAY_ANKLE_MOBILIZATION",
        NINETY_NINETY_HIP_SWITCH to "NINETY_NINETY_HIP_SWITCH",
        ACTIVE_FROG to "ACTIVE_FROG",
        SHOULDER_SWEEPS to "SHOULDER_SWEEPS",
        ANKLE_LUNGES to "ANKLE_LUNGES",
        BACK_ROLL_FOAM_ROLLER to "BACK_ROLL_FOAM_ROLLER",
        BEAR_CRAWL to "BEAR_CRAWL",
        LATISSIMUS_DORSI_FOAM_ROLL to "LATISSIMUS_DORSI_FOAM_ROLL",
        REVERSE_T_HIP_OPENER to "REVERSE_T_HIP_OPENER",
        SHOULDER_ROLLS to "SHOULDER_ROLLS",
        CHEST_OPENERS to "CHEST_OPENERS",
        TRICEPS_STRETCH to "TRICEPS_STRETCH",
        UPPER_BACK_STRETCH to "UPPER_BACK_STRETCH",
        HIP_CIRCLES to "HIP_CIRCLES",
        ANKLE_STRETCH to "ANKLE_STRETCH",
        MARCHING_IN_PLACE to "MARCHING_IN_PLACE",
        TRICEPS_STRETCH_WHEELCHAIR to "TRICEPS_STRETCH_WHEELCHAIR",
        UPPER_BACK_STRETCH_WHEELCHAIR to "UPPER_BACK_STRETCH_WHEELCHAIR"
    )

    fun getStringFromValue(value: Int?): String = stringMap[value] ?: ""

    fun getValueFromString(value: String): Int {
        for ((k, v) in stringMap) {
            if (v == value) return k
        }
        return INVALID
    }
}
